In [1]:
%load_ext autoreload

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure

%autoreload 2
%aimport AD_predictor_tools
%aimport AD_comparison_tools
%aimport PlottingTools

In [3]:
VDR_gNOMAD = pd.read_csv("../data/VDR_gnomAD_v2.1.1_12-47841538-47943049_2023_03_01_18_53_34.csv")
VDR_gNOMAD

,Chromosome,Position,rsIDs,Reference,Alternate,Source,Filters - exomes,Filters - genomes,Transcript,HGVS Consequence,...,Homozygote Count European (non-Finnish),Hemizygote Count European (non-Finnish),Allele Count Other,Allele Number Other,Homozygote Count Other,Hemizygote Count Other,Allele Count South Asian,Allele Number South Asian,Homozygote Count South Asian,Hemizygote Count South Asian
0,12,47841542,rs944146438,C,A,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
1,12,47841543,rs536743178,C,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1086,0,0,0,0,0,0
2,12,47841575,rs1464861314,T,C,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1086,0,0,0,0,0,0
3,12,47841586,rs1165350582,A,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
4,12,47841599,rs1396461999,C,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9479,12,47942998,rs1222541015,C,T,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9480,12,47942999,rs887806114,G,A,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9481,12,47943002,rs6580625,T,C,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9482,12,47943029,rs1193565929,T,C,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9483,12,47943045,rs1249132830,A,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1086,0,0,0,0,0,0

In [6]:
VDR_gNOMAD

,Chromosome,Position,rsIDs,Reference,Alternate,Source,Filters - exomes,Filters - genomes,Transcript,HGVS Consequence,...,Homozygote Count European (non-Finnish),Hemizygote Count European (non-Finnish),Allele Count Other,Allele Number Other,Homozygote Count Other,Hemizygote Count Other,Allele Count South Asian,Allele Number South Asian,Homozygote Count South Asian,Hemizygote Count South Asian
0,12,47841542,rs944146438,C,A,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
1,12,47841543,rs536743178,C,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1086,0,0,0,0,0,0
2,12,47841575,rs1464861314,T,C,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1086,0,0,0,0,0,0
3,12,47841586,rs1165350582,A,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
4,12,47841599,rs1396461999,C,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9479,12,47942998,rs1222541015,C,T,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9480,12,47942999,rs887806114,G,A,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9481,12,47943002,rs6580625,T,C,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9482,12,47943029,rs1193565929,T,C,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1088,0,0,0,0,0,0
9483,12,47943045,rs1249132830,A,G,gnomAD Genomes,NaN,PASS,NaN,NaN,...,0,0,0,1086,0,0,0,0,0,0