In [57]:
import pandas as pd
import numpy as np

In [419]:
# Do domain coordinates match what is expected?
# Let's look into pparg, 
uniprotID = "P37231"

In [420]:
tfs_tbl = pd.read_csv("../soto_analysis/outputs/all_TFs_table_proteins.txt", sep = "\t")
tfs_tbl

,Unnamed: 0,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
0,0,NaN,NaN,A6NJG6,NaN,ENST00000334384,79-135,142-315,NaN,NaN,1
1,1,NaN,NaN,A8MTJ6,NaN,ENST00000428390,145-234,369-420,NaN,NaN,1
2,2,NaN,NaN,A8MYZ6,NaN,ENST00000641094,89-178,382-491,NaN,NaN,1
3,3,NaN,NaN,A8MZ59,NaN,ENST00000640845,31-65,92-181,NaN,NaN,1
4,4,NaN,NaN,O00321,NaN,ENST00000403402,242-321,1-162,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...
441,441,NaN,NaN,Q9Y5R6,NaN,ENST00000382276,72-118,172-251,NaN,NaN,1
442,442,NaN,NaN,Q9Y5W3,NaN,ENST00000248071,"272-296,302-326,332-354",1-89,NaN,NaN,1
443,443,NaN,NaN,Q9Y692,NaN,ENST00000294409,89-165,422-573,NaN,NaN,1
444,444,NaN,NaN,Q9Y6Q9,NaN,ENST00000371998,31-83,621-1424,NaN,NaN,1
445,445,NaN,NaN,Q9Y6Y1,NaN,ENST00000303635,69-182,"702-841,422-501",NaN,NaN,1

In [421]:
tfs_tbl[tfs_tbl["uniprotID"] == uniprotID]

,Unnamed: 0,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
162,162,NaN,NaN,P37231,NaN,ENST00000287820,137-205,"12-101,495-503",NaN,NaN,1

In [422]:
ENST = tfs_tbl[tfs_tbl["uniprotID"] == uniprotID]["ENST"].iloc[0]
ENST

'ENST00000287820'

In [423]:
# CDS
cds_exons = pd.read_csv("../soto_analysis/outputs/mutations/cds_bed_format/" + ENST, sep = "\t", header = None)
#cds_exons[1] += 1
cds_exons

# Nearly matches what is expected - just that each start is one less than it needs be
# https://www.ncbi.nlm.nih.gov/CCDS/CcdsBrowse.cgi?REQUEST=CCDS&DATA=CCDS2609
# Expectation:
# 3	12351593	12351674	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3
# 3	12379704	12379931	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3
# 3	12381322	12381491	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3
# 3	12392614	12392752	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3
# 3	12405882	12406081	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3
# 3	12416704	12417154	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3
# 3	12433898	12434145	Link to NCBI NucleotideLink to UCSC Genome Browser on chromosome 3Link to Ensembl Genome Browser on chromosome 3

   0         1         2                3  4
0  3  12381321  12381491  ENST00000287820  1
1  3  12392613  12392752  ENST00000287820  1
2  3  12405881  12406081  ENST00000287820  1
3  3  12416703  12417154  ENST00000287820  1
4  3  12351592  12351674  ENST00000287820  1
5  3  12379703  12379931  ENST00000287820  1
6  3  12433897  12434145  ENST00000287820  1

In [424]:
domain_AD_exons = pd.read_csv("../soto_analysis/outputs/mutations/domains_bed_format/" + uniprotID, sep = "\t", header = None)
domain_AD_exons = domain_AD_exons[domain_AD_exons[3] == "AD"]
domain_AD_exons

   0         1         2   3   4  5  6                7
2  3  12351624  12351675  AD NaN  .  +  ENST00000287820
3  3  12379702  12379921  AD NaN  .  +  ENST00000287820
4  3  12434096  12434123  AD NaN  .  +  ENST00000287820

In [425]:
display(cds_exons)

coords = []
nt_length = 0

for i in cds_exons.index:
    line = cds_exons.loc[i]
    strand = line[4]
    chrom = line[0]
    
    if strand == "-" or strand == "-1":
        #start, end = int(line[2]), int(line[1]) + 1
        start, end = int(line[1]) + 1, int(line[2]) #SK 10/25/24
    else:
        start, end = int(line[1]) + 1, int(line[2])
        
    #print(start, end)

    coords.append((start, end))
    nt_length += abs(end - start) + 1

aa_length = int(nt_length/3)
n_exons = len(coords)

if strand == "-" or strand == -1:
    coords.sort(key=lambda _: -1 * _[0])
else:
    coords.sort(key=lambda _: 1 * _[0])

display(coords)

   0         1         2                3  4
0  3  12381321  12381491  ENST00000287820  1
1  3  12392613  12392752  ENST00000287820  1
2  3  12405881  12406081  ENST00000287820  1
3  3  12416703  12417154  ENST00000287820  1
4  3  12351592  12351674  ENST00000287820  1
5  3  12379703  12379931  ENST00000287820  1
6  3  12433897  12434145  ENST00000287820  1

[(12351593, 12351674),
 (12379704, 12379931),
 (12381322, 12381491),
 (12392614, 12392752),
 (12405882, 12406081),
 (12416704, 12417154),
 (12433898, 12434145)]

In [426]:
dict_aa_coords = {}
all_pos = []
for start, end in coords:
    if strand == "+" or strand == 1:
        all_pos += list(range(start, end + 1))
    elif strand == "-" or strand == -1:
        all_pos += list(range(end, start - 1, -1))  # SK change 10/25/24

In [427]:
start_codon = 0
for i in range(aa_length):
    end_codon = start_codon +3
    dict_aa_coords[i+1] = all_pos[start_codon : end_codon]
    start_codon += 3

In [428]:
dict_aa_coords

{1: [12351593, 12351594, 12351595],
 2: [12351596, 12351597, 12351598],
 3: [12351599, 12351600, 12351601],
 4: [12351602, 12351603, 12351604],
 5: [12351605, 12351606, 12351607],
 6: [12351608, 12351609, 12351610],
 7: [12351611, 12351612, 12351613],
 8: [12351614, 12351615, 12351616],
 9: [12351617, 12351618, 12351619],
 10: [12351620, 12351621, 12351622],
 11: [12351623, 12351624, 12351625],
 12: [12351626, 12351627, 12351628],
 13: [12351629, 12351630, 12351631],
 14: [12351632, 12351633, 12351634],
 15: [12351635, 12351636, 12351637],
 16: [12351638, 12351639, 12351640],
 17: [12351641, 12351642, 12351643],
 18: [12351644, 12351645, 12351646],
 19: [12351647, 12351648, 12351649],
 20: [12351650, 12351651, 12351652],
 21: [12351653, 12351654, 12351655],
 22: [12351656, 12351657, 12351658],
 23: [12351659, 12351660, 12351661],
 24: [12351662, 12351663, 12351664],
 25: [12351665, 12351666, 12351667],
 26: [12351668, 12351669, 12351670],
 27: [12351671, 12351672, 12351673],
 28: [12351674, 12379704, 12379705],
 29: [12379706, 12379707, 12379708],
 30: [12379709, 12379710, 12379711],
 31: [12379712, 12379713, 12379714],
 32: [12379715, 12379716, 12379717],
 33: [12379718, 12379719, 12379720],
 34: [12379721, 12379722, 12379723],
 35: [12379724, 12379725, 12379726],
 36: [12379727, 12379728, 12379729],
 37: [12379730, 12379731, 12379732],
 38: [12379733, 12379734, 12379735],
 39: [12379736, 12379737, 12379738],
 40: [12379739, 12379740, 12379741],
 41: [12379742, 12379743, 12379744],
 42: [12379745, 12379746, 12379747],
 43: [12379748, 12379749, 12379750],
 44: [12379751, 12379752, 12379753],
 45: [12379754, 12379755, 12379756],
 46: [12379757, 12379758, 12379759],
 47: [12379760, 12379761, 12379762],
 48: [12379763, 12379764, 12379765],
 49: [12379766, 12379767, 12379768],
 50: [12379769, 12379770, 12379771],
 51: [12379772, 12379773, 12379774],
 52: [12379775, 12379776, 12379777],
 53: [12379778, 12379779, 12379780],
 54: [12379781, 12379782, 12379783],
 55: [12379784, 12379785, 12379786],
 56: [12379787, 12379788, 12379789],
 57: [12379790, 12379791, 12379792],
 58: [12379793, 12379794, 12379795],
 59: [12379796, 12379797, 12379798],
 60: [12379799, 12379800, 12379801],
 61: [12379802, 12379803, 12379804],
 62: [12379805, 12379806, 12379807],
 63: [12379808, 12379809, 12379810],
 64: [12379811, 12379812, 12379813],
 65: [12379814, 12379815, 12379816],
 66: [12379817, 12379818, 12379819],
 67: [12379820, 12379821, 12379822],
 68: [12379823, 12379824, 12379825],
 69: [12379826, 12379827, 12379828],
 70: [12379829, 12379830, 12379831],
 71: [12379832, 12379833, 12379834],
 72: [12379835, 12379836, 12379837],
 73: [12379838, 12379839, 12379840],
 74: [12379841, 12379842, 12379843],
 75: [12379844, 12379845, 12379846],
 76: [12379847, 12379848, 12379849],
 77: [12379850, 12379851, 12379852],
 78: [12379853, 12379854, 12379855],
 79: [12379856, 12379857, 12379858],
 80: [12379859, 12379860, 12379861],
 81: [12379862, 12379863, 12379864],
 82: [12379865, 12379866, 12379867],
 83: [12379868, 12379869, 12379870],
 84: [12379871, 12379872, 12379873],
 85: [12379874, 12379875, 12379876],
 86: [12379877, 12379878, 12379879],
 87: [12379880, 12379881, 12379882],
 88: [12379883, 12379884, 12379885],
 89: [12379886, 12379887, 12379888],
 90: [12379889, 12379890, 12379891],
 91: [12379892, 12379893, 12379894],
 92: [12379895, 12379896, 12379897],
 93: [12379898, 12379899, 12379900],
 94: [12379901, 12379902, 12379903],
 95: [12379904, 12379905, 12379906],
 96: [12379907, 12379908, 12379909],
 97: [12379910, 12379911, 12379912],
 98: [12379913, 12379914, 12379915],
 99: [12379916, 12379917, 12379918],
 100: [12379919, 12379920, 12379921],
 101: [12379922, 12379923, 12379924],
 102: [12379925, 12379926, 12379927],
 103: [12379928, 12379929, 12379930],
 104: [12379931, 12381322, 12381323],
 105: [12381324, 12381325, 12381326],
 106: [12381327, 12381328, 12381329],
 107: [12381330, 12381331, 12381332],
 108: [12381333, 12381334, 12381335],
 109: [12381336, 12381337, 12381338],
 110: [12381339, 12381340, 12381341],
 111: [12381342, 12381343, 12381344],
 112: [12381345, 12381346, 12381347],
 113: [12381348, 12381349, 12381350],
 114: [12381351, 12381352, 12381353],
 115: [12381354, 12381355, 12381356],
 116: [12381357, 12381358, 12381359],
 117: [12381360, 12381361, 12381362],
 118: [12381363, 12381364, 12381365],
 119: [12381366, 12381367, 12381368],
 120: [12381369, 12381370, 12381371],
 121: [12381372, 12381373, 12381374],
 122: [12381375, 12381376, 12381377],
 123: [12381378, 12381379, 12381380],
 124: [12381381, 12381382, 12381383],
 125: [12381384, 12381385, 12381386],
 126: [12381387, 12381388, 12381389],
 127: [12381390, 12381391, 12381392],
 128: [12381393, 12381394, 12381395],
 129: [12381396, 12381397, 12381398],
 130: [12381399, 12381400, 12381401],
 131: [12381402, 12381403, 12381404],
 132: [12381405, 12381406, 12381407],
 133: [12381408, 12381409, 12381410],
 134: [12381411, 12381412, 12381413],
 135: [12381414, 12381415, 12381416],
 136: [12381417, 12381418, 12381419],
 137: [12381420, 12381421, 12381422],
 138: [12381423, 12381424, 12381425],
 139: [12381426, 12381427, 12381428],
 140: [12381429, 12381430, 12381431],
 141: [12381432, 12381433, 12381434],
 142: [12381435, 12381436, 12381437],
 143: [12381438, 12381439, 12381440],
 144: [12381441, 12381442, 12381443],
 145: [12381444, 12381445, 12381446],
 146: [12381447, 12381448, 12381449],
 147: [12381450, 12381451, 12381452],
 148: [12381453, 12381454, 12381455],
 149: [12381456, 12381457, 12381458],
 150: [12381459, 12381460, 12381461],
 151: [12381462, 12381463, 12381464],
 152: [12381465, 12381466, 12381467],
 153: [12381468, 12381469, 12381470],
 154: [12381471, 12381472, 12381473],
 155: [12381474, 12381475, 12381476],
 156: [12381477, 12381478, 12381479],
 157: [12381480, 12381481, 12381482],
 158: [12381483, 12381484, 12381485],
 159: [12381486, 12381487, 12381488],
 160: [12381489, 12381490, 12381491],
 161: [12392614, 12392615, 12392616],
 162: [12392617, 12392618, 12392619],
 163: [12392620, 12392621, 12392622],
 164: [12392623, 12392624, 12392625],
 165: [12392626, 12392627, 12392628],
 166: [12392629, 12392630, 12392631],
 167: [12392632, 12392633, 12392634],
 168: [12392635, 12392636, 12392637],
 169: [12392638, 12392639, 12392640],
 170: [12392641, 12392642, 12392643],
 171: [12392644, 12392645, 12392646],
 172: [12392647, 12392648, 12392649],
 173: [12392650, 12392651, 12392652],
 174: [12392653, 12392654, 12392655],
 175: [12392656, 12392657, 12392658],
 176: [12392659, 12392660, 12392661],
 177: [12392662, 12392663, 12392664],
 178: [12392665, 12392666, 12392667],
 179: [12392668, 12392669, 12392670],
 180: [12392671, 12392672, 12392673],
 181: [12392674, 12392675, 12392676],
 182: [12392677, 12392678, 12392679],
 183: [12392680, 12392681, 12392682],
 184: [12392683, 12392684, 12392685],
 185: [12392686, 12392687, 12392688],
 186: [12392689, 12392690, 12392691],
 187: [12392692, 12392693, 12392694],
 188: [12392695, 12392696, 12392697],
 189: [12392698, 12392699, 12392700],
 190: [12392701, 12392702, 12392703],
 191: [12392704, 12392705, 12392706],
 192: [12392707, 12392708, 12392709],
 193: [12392710, 12392711, 12392712],
 194: [12392713, 12392714, 12392715],
 195: [12392716, 12392717, 12392718],
 196: [12392719, 12392720, 12392721],
 197: [12392722, 12392723, 12392724],
 198: [12392725, 12392726, 12392727],
 199: [12392728, 12392729, 12392730],
 200: [12392731, 12392732, 12392733],
 201: [12392734, 12392735, 12392736],
 202: [12392737, 12392738, 12392739],
 203: [12392740, 12392741, 12392742],
 204: [12392743, 12392744, 12392745],
 205: [12392746, 12392747, 12392748],
 206: [12392749, 12392750, 12392751],
 207: [12392752, 12405882, 12405883],
 208: [12405884, 12405885, 12405886],
 209: [12405887, 12405888, 12405889],
 210: [12405890, 12405891, 12405892],
 211: [12405893, 12405894, 12405895],
 212: [12405896, 12405897, 12405898],
 213: [12405899, 12405900, 12405901],
 214: [12405902, 12405903, 12405904],
 215: [12405905, 12405906, 12405907],
 216: [12405908, 12405909, 12405910],
 217: [12405911, 12405912, 12405913],
 218: [12405914, 12405915, 12405916],
 219: [12405917, 12405918, 12405919],
 220: [12405920, 12405921, 12405922],
 221: [12405923, 12405924, 12405925],
 222: [12405926, 12405927, 12405928],
 223: [12405929, 12405930, 12405931],
 224: [12405932, 12405933, 12405934],
 225: [12405935, 12405936, 12405937],
 226: [12405938, 12405939, 12405940],
 227: [12405941, 12405942, 12405943],
 228: [12405944, 12405945, 12405946],
 229: [12405947, 12405948, 12405949],
 230: [12405950, 12405951, 12405952],
 231: [12405953, 12405954, 12405955],
 232: [12405956, 12405957, 12405958],
 233: [12405959, 12405960, 12405961],
 234: [12405962, 12405963, 12405964],
 235: [12405965, 12405966, 12405967],
 236: [12405968, 12405969, 12405970],
 237: [12405971, 12405972, 12405973],
 238: [12405974, 12405975, 12405976],
 239: [12405977, 12405978, 12405979],
 240: [12405980, 12405981, 12405982],
 241: [12405983, 12405984, 12405985],
 242: [12405986, 12405987, 12405988],
 243: [12405989, 12405990, 12405991],
 244: [12405992, 12405993, 12405994],
 245: [12405995, 12405996, 12405997],
 246: [12405998, 12405999, 12406000],
 247: [12406001, 12406002, 12406003],
 248: [12406004, 12406005, 12406006],
 249: [12406007, 12406008, 12406009],
 250: [12406010, 12406011, 12406012],
 251: [12406013, 12406014, 12406015],
 252: [12406016, 12406017, 12406018],
 253: [12406019, 12406020, 12406021],
 254: [12406022, 12406023, 12406024],
 255: [12406025, 12406026, 12406027],
 256: [12406028, 12406029, 12406030],
 257: [12406031, 12406032, 12406033],
 258: [12406034, 12406035, 12406036],
 259: [12406037, 12406038, 12406039],
 260: [12406040, 12406041, 12406042],
 261: [12406043, 12406044, 12406045],
 262: [12406046, 12406047, 12406048],
 263: [12406049, 12406050, 12406051],
 264: [12406052, 12406053, 12406054],
 265: [12406055, 12406056, 12406057],
 266: [12406058, 12406059, 12406060],
 267: [12406061, 12406062, 12406063],
 268: [12406064, 12406065, 12406066],
 269: [12406067, 12406068, 12406069],
 270: [12406070, 12406071, 12406072],
 271: [12406073, 12406074, 12406075],
 272: [12406076, 12406077, 12406078],
 273: [12406079, 12406080, 12406081],
 274: [12416704, 12416705, 12416706],
 275: [12416707, 12416708, 12416709],
 276: [12416710, 12416711, 12416712],
 277: [12416713, 12416714, 12416715],
 278: [12416716, 12416717, 12416718],
 279: [12416719, 12416720, 12416721],
 280: [12416722, 12416723, 12416724],
 281: [12416725, 12416726, 12416727],
 282: [12416728, 12416729, 12416730],
 283: [12416731, 12416732, 12416733],
 284: [12416734, 12416735, 12416736],
 285: [12416737, 12416738, 12416739],
 286: [12416740, 12416741, 12416742],
 287: [12416743, 12416744, 12416745],
 288: [12416746, 12416747, 12416748],
 289: [12416749, 12416750, 12416751],
 290: [12416752, 12416753, 12416754],
 291: [12416755, 12416756, 12416757],
 292: [12416758, 12416759, 12416760],
 293: [12416761, 12416762, 12416763],
 294: [12416764, 12416765, 12416766],
 295: [12416767, 12416768, 12416769],
 296: [12416770, 12416771, 12416772],
 297: [12416773, 12416774, 12416775],
 298: [12416776, 12416777, 12416778],
 299: [12416779, 12416780, 12416781],
 300: [12416782, 12416783, 12416784],
 301: [12416785, 12416786, 12416787],
 302: [12416788, 12416789, 12416790],
 303: [12416791, 12416792, 12416793],
 304: [12416794, 12416795, 12416796],
 305: [12416797, 12416798, 12416799],
 306: [12416800, 12416801, 12416802],
 307: [12416803, 12416804, 12416805],
 308: [12416806, 12416807, 12416808],
 309: [12416809, 12416810, 12416811],
 310: [12416812, 12416813, 12416814],
 311: [12416815, 12416816, 12416817],
 312: [12416818, 12416819, 12416820],
 313: [12416821, 12416822, 12416823],
 314: [12416824, 12416825, 12416826],
 315: [12416827, 12416828, 12416829],
 316: [12416830, 12416831, 12416832],
 317: [12416833, 12416834, 12416835],
 318: [12416836, 12416837, 12416838],
 319: [12416839, 12416840, 12416841],
 320: [12416842, 12416843, 12416844],
 321: [12416845, 12416846, 12416847],
 322: [12416848, 12416849, 12416850],
 323: [12416851, 12416852, 12416853],
 324: [12416854, 12416855, 12416856],
 325: [12416857, 12416858, 12416859],
 326: [12416860, 12416861, 12416862],
 327: [12416863, 12416864, 12416865],
 328: [12416866, 12416867, 12416868],
 329: [12416869, 12416870, 12416871],
 330: [12416872, 12416873, 12416874],
 331: [12416875, 12416876, 12416877],
 332: [12416878, 12416879, 12416880],
 333: [12416881, 12416882, 12416883],
 334: [12416884, 12416885, 12416886],
 335: [12416887, 12416888, 12416889],
 336: [12416890, 12416891, 12416892],
 337: [12416893, 12416894, 12416895],
 338: [12416896, 12416897, 12416898],
 339: [12416899, 12416900, 12416901],
 340: [12416902, 12416903, 12416904],
 341: [12416905, 12416906, 12416907],
 342: [12416908, 12416909, 12416910],
 343: [12416911, 12416912, 12416913],
 344: [12416914, 12416915, 12416916],
 345: [12416917, 12416918, 12416919],
 346: [12416920, 12416921, 12416922],
 347: [12416923, 12416924, 12416925],
 348: [12416926, 12416927, 12416928],
 349: [12416929, 12416930, 12416931],
 350: [12416932, 12416933, 12416934],
 351: [12416935, 12416936, 12416937],
 352: [12416938, 12416939, 12416940],
 353: [12416941, 12416942, 12416943],
 354: [12416944, 12416945, 12416946],
 355: [12416947, 12416948, 12416949],
 356: [12416950, 12416951, 12416952],
 357: [12416953, 12416954, 12416955],
 358: [12416956, 12416957, 12416958],
 359: [12416959, 12416960, 12416961],
 360: [12416962, 12416963, 12416964],
 361: [12416965, 12416966, 12416967],
 362: [12416968, 12416969, 12416970],
 363: [12416971, 12416972, 12416973],
 364: [12416974, 12416975, 12416976],
 365: [12416977, 12416978, 12416979],
 366: [12416980, 12416981, 12416982],
 367: [12416983, 12416984, 12416985],
 368: [12416986, 12416987, 12416988],
 369: [12416989, 12416990, 12416991],
 370: [12416992, 12416993, 12416994],
 371: [12416995, 12416996, 12416997],
 372: [12416998, 12416999, 12417000],
 373: [12417001, 12417002, 12417003],
 374: [12417004, 12417005, 12417006],
 375: [12417007, 12417008, 12417009],
 376: [12417010, 12417011, 12417012],
 377: [12417013, 12417014, 12417015],
 378: [12417016, 12417017, 12417018],
 379: [12417019, 12417020, 12417021],
 380: [12417022, 12417023, 12417024],
 381: [12417025, 12417026, 12417027],
 382: [12417028, 12417029, 12417030],
 383: [12417031, 12417032, 12417033],
 384: [12417034, 12417035, 12417036],
 385: [12417037, 12417038, 12417039],
 386: [12417040, 12417041, 12417042],
 387: [12417043, 12417044, 12417045],
 388: [12417046, 12417047, 12417048],
 389: [12417049, 12417050, 12417051],
 390: [12417052, 12417053, 12417054],
 391: [12417055, 12417056, 12417057],
 392: [12417058, 12417059, 12417060],
 393: [12417061, 12417062, 12417063],
 394: [12417064, 12417065, 12417066],
 395: [12417067, 12417068, 12417069],
 396: [12417070, 12417071, 12417072],
 397: [12417073, 12417074, 12417075],
 398: [12417076, 12417077, 12417078],
 399: [12417079, 12417080, 12417081],
 400: [12417082, 12417083, 12417084],
 401: [12417085, 12417086, 12417087],
 402: [12417088, 12417089, 12417090],
 403: [12417091, 12417092, 12417093],
 404: [12417094, 12417095, 12417096],
 405: [12417097, 12417098, 12417099],
 406: [12417100, 12417101, 12417102],
 407: [12417103, 12417104, 12417105],
 408: [12417106, 12417107, 12417108],
 409: [12417109, 12417110, 12417111],
 410: [12417112, 12417113, 12417114],
 411: [12417115, 12417116, 12417117],
 412: [12417118, 12417119, 12417120],
 413: [12417121, 12417122, 12417123],
 414: [12417124, 12417125, 12417126],
 415: [12417127, 12417128, 12417129],
 416: [12417130, 12417131, 12417132],
 417: [12417133, 12417134, 12417135],
 418: [12417136, 12417137, 12417138],
 419: [12417139, 12417140, 12417141],
 420: [12417142, 12417143, 12417144],
 421: [12417145, 12417146, 12417147],
 422: [12417148, 12417149, 12417150],
 423: [12417151, 12417152, 12417153],
 424: [12417154, 12433898, 12433899],
 425: [12433900, 12433901, 12433902],
 426: [12433903, 12433904, 12433905],
 427: [12433906, 12433907, 12433908],
 428: [12433909, 12433910, 12433911],
 429: [12433912, 12433913, 12433914],
 430: [12433915, 12433916, 12433917],
 431: [12433918, 12433919, 12433920],
 432: [12433921, 12433922, 12433923],
 433: [12433924, 12433925, 12433926],
 434: [12433927, 12433928, 12433929],
 435: [12433930, 12433931, 12433932],
 436: [12433933, 12433934, 12433935],
 437: [12433936, 12433937, 12433938],
 438: [12433939, 12433940, 12433941],
 439: [12433942, 12433943, 12433944],
 440: [12433945, 12433946, 12433947],
 441: [12433948, 12433949, 12433950],
 442: [12433951, 12433952, 12433953],
 443: [12433954, 12433955, 12433956],
 444: [12433957, 12433958, 12433959],
 445: [12433960, 12433961, 12433962],
 446: [12433963, 12433964, 12433965],
 447: [12433966, 12433967, 12433968],
 448: [12433969, 12433970, 12433971],
 449: [12433972, 12433973, 12433974],
 450: [12433975, 12433976, 12433977],
 451: [12433978, 12433979, 12433980],
 452: [12433981, 12433982, 12433983],
 453: [12433984, 12433985, 12433986],
 454: [12433987, 12433988, 12433989],
 455: [12433990, 12433991, 12433992],
 456: [12433993, 12433994, 12433995],
 457: [12433996, 12433997, 12433998],
 458: [12433999, 12434000, 12434001],
 459: [12434002, 12434003, 12434004],
 460: [12434005, 12434006, 12434007],
 461: [12434008, 12434009, 12434010],
 462: [12434011, 12434012, 12434013],
 463: [12434014, 12434015, 12434016],
 464: [12434017, 12434018, 12434019],
 465: [12434020, 12434021, 12434022],
 466: [12434023, 12434024, 12434025],
 467: [12434026, 12434027, 12434028],
 468: [12434029, 12434030, 12434031],
 469: [12434032, 12434033, 12434034],
 470: [12434035, 12434036, 12434037],
 471: [12434038, 12434039, 12434040],
 472: [12434041, 12434042, 12434043],
 473: [12434044, 12434045, 12434046],
 474: [12434047, 12434048, 12434049],
 475: [12434050, 12434051, 12434052],
 476: [12434053, 12434054, 12434055],
 477: [12434056, 12434057, 12434058],
 478: [12434059, 12434060, 12434061],
 479: [12434062, 12434063, 12434064],
 480: [12434065, 12434066, 12434067],
 481: [12434068, 12434069, 12434070],
 482: [12434071, 12434072, 12434073],
 483: [12434074, 12434075, 12434076],
 484: [12434077, 12434078, 12434079],
 485: [12434080, 12434081, 12434082],
 486: [12434083, 12434084, 12434085],
 487: [12434086, 12434087, 12434088],
 488: [12434089, 12434090, 12434091],
 489: [12434092, 12434093, 12434094],
 490: [12434095, 12434096, 12434097],
 491: [12434098, 12434099, 12434100],
 492: [12434101, 12434102, 12434103],
 493: [12434104, 12434105, 12434106],
 494: [12434107, 12434108, 12434109],
 495: [12434110, 12434111, 12434112],
 496: [12434113, 12434114, 12434115],
 497: [12434116, 12434117, 12434118],
 498: [12434119, 12434120, 12434121],
 499: [12434122, 12434123, 12434124],
 500: [12434125, 12434126, 12434127],
 501: [12434128, 12434129, 12434130],
 502: [12434131, 12434132, 12434133],
 503: [12434134, 12434135, 12434136],
 504: [12434137, 12434138, 12434139],
 505: [12434140, 12434141, 12434142],
 506: [12434143, 12434144, 12434145]}

In [429]:
def split_coords(data, strand):
	# https://stackoverflow.com/questions/3149440/splitting-list-based-on-missing-numbers-in-a-sequence
	output = []
	if strand == "-" or strand == -1:
		data.reverse()
	for k, g in groupby(enumerate(data), lambda i_x: i_x[0] - i_x[1]):
		output.append(list(map(itemgetter(1), g)))
	return output

In [430]:
import math
from itertools import groupby
from operator import itemgetter
import os

domain = "AD"

#433-479,118-261

for start_dom, end_dom in zip([433,118], [479, 261]):
    print(start_dom, end_dom)
    #if to_print:
        #print(start_dom, end_dom, domain)
    dom_pos = []
    for aa in range(start_dom, end_dom +1):
        dom_pos += dict_aa_coords[aa]

    #if to_print:
        #print(dom_pos,strand)
    #print(dom_pos)
    
    for cds_dom in split_coords(dom_pos, strand):
        #print(cds_dom)
        start_bed = cds_dom[0] - 1
        end_bed = cds_dom[-1]
        #print(str(chrom) + "\t" + str(start_bed) + "\t" + str(end_bed) + "\t" + name + "\t" + ensg + "\t.\t" + strand + "\t" + enst + "\n")

        if strand == -1:
            new_strand = "-"
        else:
            new_strand = "+"
        print(str(chrom) + "\t" + str(start_bed) + "\t" + str(end_bed) + "\t" + "" + "\t" + "" + "\t.\t" + new_strand + "\t" + "" + "\n")
        #print(tf, name, start_bed, end_bed)

433 479
3	12433923	12434064			.	+

118 261
3	12381362	12381491			.	+

3	12392613	12392752			.	+

3	12405881	12406045			.	+

In [431]:
[[38383406, 38383546],
 [38392407, 38392444],
 [38400574, 38400645],
 [38402557, 38402637],
 [38403506, 38403709],
 [38423410, 38423446]]

[[38383406, 38383546],
 [38392407, 38392444],
 [38400574, 38400645],
 [38402557, 38402637],
 [38403506, 38403709],
 [38423410, 38423446]]

In [432]:
cds_exons_expanded

     positions  prot_pos     AD  AD_bed
0     38498380         1  False   False
1     38498379         1  False   False
2     38498378         1  False    True
3     38498377         2  False    True
4     38498376         2  False    True
...        ...       ...    ...     ...
1435  38383407       479   True    True
1436  38383406       479   True    True
1437  38383405       480  False    True
1438  38383404       480  False    True
1439  38383403       480  False    True

[1440 rows x 4 columns]

In [433]:
dict_aa_coords

{1: [12351593, 12351594, 12351595],
 2: [12351596, 12351597, 12351598],
 3: [12351599, 12351600, 12351601],
 4: [12351602, 12351603, 12351604],
 5: [12351605, 12351606, 12351607],
 6: [12351608, 12351609, 12351610],
 7: [12351611, 12351612, 12351613],
 8: [12351614, 12351615, 12351616],
 9: [12351617, 12351618, 12351619],
 10: [12351620, 12351621, 12351622],
 11: [12351623, 12351624, 12351625],
 12: [12351626, 12351627, 12351628],
 13: [12351629, 12351630, 12351631],
 14: [12351632, 12351633, 12351634],
 15: [12351635, 12351636, 12351637],
 16: [12351638, 12351639, 12351640],
 17: [12351641, 12351642, 12351643],
 18: [12351644, 12351645, 12351646],
 19: [12351647, 12351648, 12351649],
 20: [12351650, 12351651, 12351652],
 21: [12351653, 12351654, 12351655],
 22: [12351656, 12351657, 12351658],
 23: [12351659, 12351660, 12351661],
 24: [12351662, 12351663, 12351664],
 25: [12351665, 12351666, 12351667],
 26: [12351668, 12351669, 12351670],
 27: [12351671, 12351672, 12351673],
 28: [12351674, 12379704, 12379705],
 29: [12379706, 12379707, 12379708],
 30: [12379709, 12379710, 12379711],
 31: [12379712, 12379713, 12379714],
 32: [12379715, 12379716, 12379717],
 33: [12379718, 12379719, 12379720],
 34: [12379721, 12379722, 12379723],
 35: [12379724, 12379725, 12379726],
 36: [12379727, 12379728, 12379729],
 37: [12379730, 12379731, 12379732],
 38: [12379733, 12379734, 12379735],
 39: [12379736, 12379737, 12379738],
 40: [12379739, 12379740, 12379741],
 41: [12379742, 12379743, 12379744],
 42: [12379745, 12379746, 12379747],
 43: [12379748, 12379749, 12379750],
 44: [12379751, 12379752, 12379753],
 45: [12379754, 12379755, 12379756],
 46: [12379757, 12379758, 12379759],
 47: [12379760, 12379761, 12379762],
 48: [12379763, 12379764, 12379765],
 49: [12379766, 12379767, 12379768],
 50: [12379769, 12379770, 12379771],
 51: [12379772, 12379773, 12379774],
 52: [12379775, 12379776, 12379777],
 53: [12379778, 12379779, 12379780],
 54: [12379781, 12379782, 12379783],
 55: [12379784, 12379785, 12379786],
 56: [12379787, 12379788, 12379789],
 57: [12379790, 12379791, 12379792],
 58: [12379793, 12379794, 12379795],
 59: [12379796, 12379797, 12379798],
 60: [12379799, 12379800, 12379801],
 61: [12379802, 12379803, 12379804],
 62: [12379805, 12379806, 12379807],
 63: [12379808, 12379809, 12379810],
 64: [12379811, 12379812, 12379813],
 65: [12379814, 12379815, 12379816],
 66: [12379817, 12379818, 12379819],
 67: [12379820, 12379821, 12379822],
 68: [12379823, 12379824, 12379825],
 69: [12379826, 12379827, 12379828],
 70: [12379829, 12379830, 12379831],
 71: [12379832, 12379833, 12379834],
 72: [12379835, 12379836, 12379837],
 73: [12379838, 12379839, 12379840],
 74: [12379841, 12379842, 12379843],
 75: [12379844, 12379845, 12379846],
 76: [12379847, 12379848, 12379849],
 77: [12379850, 12379851, 12379852],
 78: [12379853, 12379854, 12379855],
 79: [12379856, 12379857, 12379858],
 80: [12379859, 12379860, 12379861],
 81: [12379862, 12379863, 12379864],
 82: [12379865, 12379866, 12379867],
 83: [12379868, 12379869, 12379870],
 84: [12379871, 12379872, 12379873],
 85: [12379874, 12379875, 12379876],
 86: [12379877, 12379878, 12379879],
 87: [12379880, 12379881, 12379882],
 88: [12379883, 12379884, 12379885],
 89: [12379886, 12379887, 12379888],
 90: [12379889, 12379890, 12379891],
 91: [12379892, 12379893, 12379894],
 92: [12379895, 12379896, 12379897],
 93: [12379898, 12379899, 12379900],
 94: [12379901, 12379902, 12379903],
 95: [12379904, 12379905, 12379906],
 96: [12379907, 12379908, 12379909],
 97: [12379910, 12379911, 12379912],
 98: [12379913, 12379914, 12379915],
 99: [12379916, 12379917, 12379918],
 100: [12379919, 12379920, 12379921],
 101: [12379922, 12379923, 12379924],
 102: [12379925, 12379926, 12379927],
 103: [12379928, 12379929, 12379930],
 104: [12379931, 12381322, 12381323],
 105: [12381324, 12381325, 12381326],
 106: [12381327, 12381328, 12381329],
 107: [12381330, 12381331, 12381332],
 108: [12381333, 12381334, 12381335],
 109: [12381336, 12381337, 12381338],
 110: [12381339, 12381340, 12381341],
 111: [12381342, 12381343, 12381344],
 112: [12381345, 12381346, 12381347],
 113: [12381348, 12381349, 12381350],
 114: [12381351, 12381352, 12381353],
 115: [12381354, 12381355, 12381356],
 116: [12381357, 12381358, 12381359],
 117: [12381360, 12381361, 12381362],
 118: [12381363, 12381364, 12381365],
 119: [12381366, 12381367, 12381368],
 120: [12381369, 12381370, 12381371],
 121: [12381372, 12381373, 12381374],
 122: [12381375, 12381376, 12381377],
 123: [12381378, 12381379, 12381380],
 124: [12381381, 12381382, 12381383],
 125: [12381384, 12381385, 12381386],
 126: [12381387, 12381388, 12381389],
 127: [12381390, 12381391, 12381392],
 128: [12381393, 12381394, 12381395],
 129: [12381396, 12381397, 12381398],
 130: [12381399, 12381400, 12381401],
 131: [12381402, 12381403, 12381404],
 132: [12381405, 12381406, 12381407],
 133: [12381408, 12381409, 12381410],
 134: [12381411, 12381412, 12381413],
 135: [12381414, 12381415, 12381416],
 136: [12381417, 12381418, 12381419],
 137: [12381420, 12381421, 12381422],
 138: [12381423, 12381424, 12381425],
 139: [12381426, 12381427, 12381428],
 140: [12381429, 12381430, 12381431],
 141: [12381432, 12381433, 12381434],
 142: [12381435, 12381436, 12381437],
 143: [12381438, 12381439, 12381440],
 144: [12381441, 12381442, 12381443],
 145: [12381444, 12381445, 12381446],
 146: [12381447, 12381448, 12381449],
 147: [12381450, 12381451, 12381452],
 148: [12381453, 12381454, 12381455],
 149: [12381456, 12381457, 12381458],
 150: [12381459, 12381460, 12381461],
 151: [12381462, 12381463, 12381464],
 152: [12381465, 12381466, 12381467],
 153: [12381468, 12381469, 12381470],
 154: [12381471, 12381472, 12381473],
 155: [12381474, 12381475, 12381476],
 156: [12381477, 12381478, 12381479],
 157: [12381480, 12381481, 12381482],
 158: [12381483, 12381484, 12381485],
 159: [12381486, 12381487, 12381488],
 160: [12381489, 12381490, 12381491],
 161: [12392614, 12392615, 12392616],
 162: [12392617, 12392618, 12392619],
 163: [12392620, 12392621, 12392622],
 164: [12392623, 12392624, 12392625],
 165: [12392626, 12392627, 12392628],
 166: [12392629, 12392630, 12392631],
 167: [12392632, 12392633, 12392634],
 168: [12392635, 12392636, 12392637],
 169: [12392638, 12392639, 12392640],
 170: [12392641, 12392642, 12392643],
 171: [12392644, 12392645, 12392646],
 172: [12392647, 12392648, 12392649],
 173: [12392650, 12392651, 12392652],
 174: [12392653, 12392654, 12392655],
 175: [12392656, 12392657, 12392658],
 176: [12392659, 12392660, 12392661],
 177: [12392662, 12392663, 12392664],
 178: [12392665, 12392666, 12392667],
 179: [12392668, 12392669, 12392670],
 180: [12392671, 12392672, 12392673],
 181: [12392674, 12392675, 12392676],
 182: [12392677, 12392678, 12392679],
 183: [12392680, 12392681, 12392682],
 184: [12392683, 12392684, 12392685],
 185: [12392686, 12392687, 12392688],
 186: [12392689, 12392690, 12392691],
 187: [12392692, 12392693, 12392694],
 188: [12392695, 12392696, 12392697],
 189: [12392698, 12392699, 12392700],
 190: [12392701, 12392702, 12392703],
 191: [12392704, 12392705, 12392706],
 192: [12392707, 12392708, 12392709],
 193: [12392710, 12392711, 12392712],
 194: [12392713, 12392714, 12392715],
 195: [12392716, 12392717, 12392718],
 196: [12392719, 12392720, 12392721],
 197: [12392722, 12392723, 12392724],
 198: [12392725, 12392726, 12392727],
 199: [12392728, 12392729, 12392730],
 200: [12392731, 12392732, 12392733],
 201: [12392734, 12392735, 12392736],
 202: [12392737, 12392738, 12392739],
 203: [12392740, 12392741, 12392742],
 204: [12392743, 12392744, 12392745],
 205: [12392746, 12392747, 12392748],
 206: [12392749, 12392750, 12392751],
 207: [12392752, 12405882, 12405883],
 208: [12405884, 12405885, 12405886],
 209: [12405887, 12405888, 12405889],
 210: [12405890, 12405891, 12405892],
 211: [12405893, 12405894, 12405895],
 212: [12405896, 12405897, 12405898],
 213: [12405899, 12405900, 12405901],
 214: [12405902, 12405903, 12405904],
 215: [12405905, 12405906, 12405907],
 216: [12405908, 12405909, 12405910],
 217: [12405911, 12405912, 12405913],
 218: [12405914, 12405915, 12405916],
 219: [12405917, 12405918, 12405919],
 220: [12405920, 12405921, 12405922],
 221: [12405923, 12405924, 12405925],
 222: [12405926, 12405927, 12405928],
 223: [12405929, 12405930, 12405931],
 224: [12405932, 12405933, 12405934],
 225: [12405935, 12405936, 12405937],
 226: [12405938, 12405939, 12405940],
 227: [12405941, 12405942, 12405943],
 228: [12405944, 12405945, 12405946],
 229: [12405947, 12405948, 12405949],
 230: [12405950, 12405951, 12405952],
 231: [12405953, 12405954, 12405955],
 232: [12405956, 12405957, 12405958],
 233: [12405959, 12405960, 12405961],
 234: [12405962, 12405963, 12405964],
 235: [12405965, 12405966, 12405967],
 236: [12405968, 12405969, 12405970],
 237: [12405971, 12405972, 12405973],
 238: [12405974, 12405975, 12405976],
 239: [12405977, 12405978, 12405979],
 240: [12405980, 12405981, 12405982],
 241: [12405983, 12405984, 12405985],
 242: [12405986, 12405987, 12405988],
 243: [12405989, 12405990, 12405991],
 244: [12405992, 12405993, 12405994],
 245: [12405995, 12405996, 12405997],
 246: [12405998, 12405999, 12406000],
 247: [12406001, 12406002, 12406003],
 248: [12406004, 12406005, 12406006],
 249: [12406007, 12406008, 12406009],
 250: [12406010, 12406011, 12406012],
 251: [12406013, 12406014, 12406015],
 252: [12406016, 12406017, 12406018],
 253: [12406019, 12406020, 12406021],
 254: [12406022, 12406023, 12406024],
 255: [12406025, 12406026, 12406027],
 256: [12406028, 12406029, 12406030],
 257: [12406031, 12406032, 12406033],
 258: [12406034, 12406035, 12406036],
 259: [12406037, 12406038, 12406039],
 260: [12406040, 12406041, 12406042],
 261: [12406043, 12406044, 12406045],
 262: [12406046, 12406047, 12406048],
 263: [12406049, 12406050, 12406051],
 264: [12406052, 12406053, 12406054],
 265: [12406055, 12406056, 12406057],
 266: [12406058, 12406059, 12406060],
 267: [12406061, 12406062, 12406063],
 268: [12406064, 12406065, 12406066],
 269: [12406067, 12406068, 12406069],
 270: [12406070, 12406071, 12406072],
 271: [12406073, 12406074, 12406075],
 272: [12406076, 12406077, 12406078],
 273: [12406079, 12406080, 12406081],
 274: [12416704, 12416705, 12416706],
 275: [12416707, 12416708, 12416709],
 276: [12416710, 12416711, 12416712],
 277: [12416713, 12416714, 12416715],
 278: [12416716, 12416717, 12416718],
 279: [12416719, 12416720, 12416721],
 280: [12416722, 12416723, 12416724],
 281: [12416725, 12416726, 12416727],
 282: [12416728, 12416729, 12416730],
 283: [12416731, 12416732, 12416733],
 284: [12416734, 12416735, 12416736],
 285: [12416737, 12416738, 12416739],
 286: [12416740, 12416741, 12416742],
 287: [12416743, 12416744, 12416745],
 288: [12416746, 12416747, 12416748],
 289: [12416749, 12416750, 12416751],
 290: [12416752, 12416753, 12416754],
 291: [12416755, 12416756, 12416757],
 292: [12416758, 12416759, 12416760],
 293: [12416761, 12416762, 12416763],
 294: [12416764, 12416765, 12416766],
 295: [12416767, 12416768, 12416769],
 296: [12416770, 12416771, 12416772],
 297: [12416773, 12416774, 12416775],
 298: [12416776, 12416777, 12416778],
 299: [12416779, 12416780, 12416781],
 300: [12416782, 12416783, 12416784],
 301: [12416785, 12416786, 12416787],
 302: [12416788, 12416789, 12416790],
 303: [12416791, 12416792, 12416793],
 304: [12416794, 12416795, 12416796],
 305: [12416797, 12416798, 12416799],
 306: [12416800, 12416801, 12416802],
 307: [12416803, 12416804, 12416805],
 308: [12416806, 12416807, 12416808],
 309: [12416809, 12416810, 12416811],
 310: [12416812, 12416813, 12416814],
 311: [12416815, 12416816, 12416817],
 312: [12416818, 12416819, 12416820],
 313: [12416821, 12416822, 12416823],
 314: [12416824, 12416825, 12416826],
 315: [12416827, 12416828, 12416829],
 316: [12416830, 12416831, 12416832],
 317: [12416833, 12416834, 12416835],
 318: [12416836, 12416837, 12416838],
 319: [12416839, 12416840, 12416841],
 320: [12416842, 12416843, 12416844],
 321: [12416845, 12416846, 12416847],
 322: [12416848, 12416849, 12416850],
 323: [12416851, 12416852, 12416853],
 324: [12416854, 12416855, 12416856],
 325: [12416857, 12416858, 12416859],
 326: [12416860, 12416861, 12416862],
 327: [12416863, 12416864, 12416865],
 328: [12416866, 12416867, 12416868],
 329: [12416869, 12416870, 12416871],
 330: [12416872, 12416873, 12416874],
 331: [12416875, 12416876, 12416877],
 332: [12416878, 12416879, 12416880],
 333: [12416881, 12416882, 12416883],
 334: [12416884, 12416885, 12416886],
 335: [12416887, 12416888, 12416889],
 336: [12416890, 12416891, 12416892],
 337: [12416893, 12416894, 12416895],
 338: [12416896, 12416897, 12416898],
 339: [12416899, 12416900, 12416901],
 340: [12416902, 12416903, 12416904],
 341: [12416905, 12416906, 12416907],
 342: [12416908, 12416909, 12416910],
 343: [12416911, 12416912, 12416913],
 344: [12416914, 12416915, 12416916],
 345: [12416917, 12416918, 12416919],
 346: [12416920, 12416921, 12416922],
 347: [12416923, 12416924, 12416925],
 348: [12416926, 12416927, 12416928],
 349: [12416929, 12416930, 12416931],
 350: [12416932, 12416933, 12416934],
 351: [12416935, 12416936, 12416937],
 352: [12416938, 12416939, 12416940],
 353: [12416941, 12416942, 12416943],
 354: [12416944, 12416945, 12416946],
 355: [12416947, 12416948, 12416949],
 356: [12416950, 12416951, 12416952],
 357: [12416953, 12416954, 12416955],
 358: [12416956, 12416957, 12416958],
 359: [12416959, 12416960, 12416961],
 360: [12416962, 12416963, 12416964],
 361: [12416965, 12416966, 12416967],
 362: [12416968, 12416969, 12416970],
 363: [12416971, 12416972, 12416973],
 364: [12416974, 12416975, 12416976],
 365: [12416977, 12416978, 12416979],
 366: [12416980, 12416981, 12416982],
 367: [12416983, 12416984, 12416985],
 368: [12416986, 12416987, 12416988],
 369: [12416989, 12416990, 12416991],
 370: [12416992, 12416993, 12416994],
 371: [12416995, 12416996, 12416997],
 372: [12416998, 12416999, 12417000],
 373: [12417001, 12417002, 12417003],
 374: [12417004, 12417005, 12417006],
 375: [12417007, 12417008, 12417009],
 376: [12417010, 12417011, 12417012],
 377: [12417013, 12417014, 12417015],
 378: [12417016, 12417017, 12417018],
 379: [12417019, 12417020, 12417021],
 380: [12417022, 12417023, 12417024],
 381: [12417025, 12417026, 12417027],
 382: [12417028, 12417029, 12417030],
 383: [12417031, 12417032, 12417033],
 384: [12417034, 12417035, 12417036],
 385: [12417037, 12417038, 12417039],
 386: [12417040, 12417041, 12417042],
 387: [12417043, 12417044, 12417045],
 388: [12417046, 12417047, 12417048],
 389: [12417049, 12417050, 12417051],
 390: [12417052, 12417053, 12417054],
 391: [12417055, 12417056, 12417057],
 392: [12417058, 12417059, 12417060],
 393: [12417061, 12417062, 12417063],
 394: [12417064, 12417065, 12417066],
 395: [12417067, 12417068, 12417069],
 396: [12417070, 12417071, 12417072],
 397: [12417073, 12417074, 12417075],
 398: [12417076, 12417077, 12417078],
 399: [12417079, 12417080, 12417081],
 400: [12417082, 12417083, 12417084],
 401: [12417085, 12417086, 12417087],
 402: [12417088, 12417089, 12417090],
 403: [12417091, 12417092, 12417093],
 404: [12417094, 12417095, 12417096],
 405: [12417097, 12417098, 12417099],
 406: [12417100, 12417101, 12417102],
 407: [12417103, 12417104, 12417105],
 408: [12417106, 12417107, 12417108],
 409: [12417109, 12417110, 12417111],
 410: [12417112, 12417113, 12417114],
 411: [12417115, 12417116, 12417117],
 412: [12417118, 12417119, 12417120],
 413: [12417121, 12417122, 12417123],
 414: [12417124, 12417125, 12417126],
 415: [12417127, 12417128, 12417129],
 416: [12417130, 12417131, 12417132],
 417: [12417133, 12417134, 12417135],
 418: [12417136, 12417137, 12417138],
 419: [12417139, 12417140, 12417141],
 420: [12417142, 12417143, 12417144],
 421: [12417145, 12417146, 12417147],
 422: [12417148, 12417149, 12417150],
 423: [12417151, 12417152, 12417153],
 424: [12417154, 12433898, 12433899],
 425: [12433900, 12433901, 12433902],
 426: [12433903, 12433904, 12433905],
 427: [12433906, 12433907, 12433908],
 428: [12433909, 12433910, 12433911],
 429: [12433912, 12433913, 12433914],
 430: [12433915, 12433916, 12433917],
 431: [12433918, 12433919, 12433920],
 432: [12433921, 12433922, 12433923],
 433: [12433924, 12433925, 12433926],
 434: [12433927, 12433928, 12433929],
 435: [12433930, 12433931, 12433932],
 436: [12433933, 12433934, 12433935],
 437: [12433936, 12433937, 12433938],
 438: [12433939, 12433940, 12433941],
 439: [12433942, 12433943, 12433944],
 440: [12433945, 12433946, 12433947],
 441: [12433948, 12433949, 12433950],
 442: [12433951, 12433952, 12433953],
 443: [12433954, 12433955, 12433956],
 444: [12433957, 12433958, 12433959],
 445: [12433960, 12433961, 12433962],
 446: [12433963, 12433964, 12433965],
 447: [12433966, 12433967, 12433968],
 448: [12433969, 12433970, 12433971],
 449: [12433972, 12433973, 12433974],
 450: [12433975, 12433976, 12433977],
 451: [12433978, 12433979, 12433980],
 452: [12433981, 12433982, 12433983],
 453: [12433984, 12433985, 12433986],
 454: [12433987, 12433988, 12433989],
 455: [12433990, 12433991, 12433992],
 456: [12433993, 12433994, 12433995],
 457: [12433996, 12433997, 12433998],
 458: [12433999, 12434000, 12434001],
 459: [12434002, 12434003, 12434004],
 460: [12434005, 12434006, 12434007],
 461: [12434008, 12434009, 12434010],
 462: [12434011, 12434012, 12434013],
 463: [12434014, 12434015, 12434016],
 464: [12434017, 12434018, 12434019],
 465: [12434020, 12434021, 12434022],
 466: [12434023, 12434024, 12434025],
 467: [12434026, 12434027, 12434028],
 468: [12434029, 12434030, 12434031],
 469: [12434032, 12434033, 12434034],
 470: [12434035, 12434036, 12434037],
 471: [12434038, 12434039, 12434040],
 472: [12434041, 12434042, 12434043],
 473: [12434044, 12434045, 12434046],
 474: [12434047, 12434048, 12434049],
 475: [12434050, 12434051, 12434052],
 476: [12434053, 12434054, 12434055],
 477: [12434056, 12434057, 12434058],
 478: [12434059, 12434060, 12434061],
 479: [12434062, 12434063, 12434064],
 480: [12434065, 12434066, 12434067],
 481: [12434068, 12434069, 12434070],
 482: [12434071, 12434072, 12434073],
 483: [12434074, 12434075, 12434076],
 484: [12434077, 12434078, 12434079],
 485: [12434080, 12434081, 12434082],
 486: [12434083, 12434084, 12434085],
 487: [12434086, 12434087, 12434088],
 488: [12434089, 12434090, 12434091],
 489: [12434092, 12434093, 12434094],
 490: [12434095, 12434096, 12434097],
 491: [12434098, 12434099, 12434100],
 492: [12434101, 12434102, 12434103],
 493: [12434104, 12434105, 12434106],
 494: [12434107, 12434108, 12434109],
 495: [12434110, 12434111, 12434112],
 496: [12434113, 12434114, 12434115],
 497: [12434116, 12434117, 12434118],
 498: [12434119, 12434120, 12434121],
 499: [12434122, 12434123, 12434124],
 500: [12434125, 12434126, 12434127],
 501: [12434128, 12434129, 12434130],
 502: [12434131, 12434132, 12434133],
 503: [12434134, 12434135, 12434136],
 504: [12434137, 12434138, 12434139],
 505: [12434140, 12434141, 12434142],
 506: [12434143, 12434144, 12434145]}

In [434]:
len(set(all_pos))

1518

In [435]:
cds_exons.sort_values(1)

   0         1         2                3  4
4  3  12351592  12351674  ENST00000287820  1
5  3  12379703  12379931  ENST00000287820  1
0  3  12381321  12381491  ENST00000287820  1
1  3  12392613  12392752  ENST00000287820  1
2  3  12405881  12406081  ENST00000287820  1
3  3  12416703  12417154  ENST00000287820  1
6  3  12433897  12434145  ENST00000287820  1

In [436]:
cds_exons["positions"] = [np.arange(start + 1, end + 1) for start, end in zip(cds_exons[1], cds_exons[2])]
cds_exons_expanded = cds_exons[["positions"]].explode(column = "positions")
cds_exons_expanded = cds_exons_expanded.sort_values(by = "positions", ascending = False) # should alr be sorted, just checking again
cds_exons_expanded = cds_exons_expanded.reset_index(drop = True)
cds_exons_expanded

     positions
0     12434145
1     12434144
2     12434143
3     12434142
4     12434141
...        ...
1513  12351597
1514  12351596
1515  12351595
1516  12351594
1517  12351593

[1518 rows x 1 columns]

In [437]:
tfs_tbl[tfs_tbl["uniprotID"] == uniprotID]

,Unnamed: 0,1,2,uniprotID,ENSG,ENST,DBD_coords,AD_coords,RD_coords,Bif_coords,length
162,162,NaN,NaN,P37231,NaN,ENST00000287820,137-205,"12-101,495-503",NaN,NaN,1

In [438]:
cds_exons_expanded["prot_pos"] = 1 + np.array(cds_exons_expanded.index) // 3
cds_exons_expanded

     positions  prot_pos
0     12434145         1
1     12434144         1
2     12434143         1
3     12434142         2
4     12434141         2
...        ...       ...
1513  12351597       505
1514  12351596       505
1515  12351595       506
1516  12351594       506
1517  12351593       506

[1518 rows x 2 columns]

In [440]:
cds_exons_expanded["AD"] = ((12 <= cds_exons_expanded["prot_pos"]) & (cds_exons_expanded["prot_pos"] <= 101)) \
                     | ((495 <= cds_exons_expanded["prot_pos"]) & (cds_exons_expanded["prot_pos"] <= 503))
cds_exons_expanded


#433-479,118-261

     positions  prot_pos     AD
0     12434145         1  False
1     12434144         1  False
2     12434143         1  False
3     12434142         2  False
4     12434141         2  False
...        ...       ...    ...
1513  12351597       505  False
1514  12351596       505  False
1515  12351595       506  False
1516  12351594       506  False
1517  12351593       506  False

[1518 rows x 3 columns]

In [441]:
AD_genom_pos = cds_exons_expanded[cds_exons_expanded["AD"]]["positions"]
AD_genom_pos

33      12434112
34      12434111
35      12434110
36      12434109
37      12434108
          ...
1504    12351606
1505    12351605
1506    12351604
1507    12351603
1508    12351602
Name: positions, Length: 297, dtype: object

In [442]:
#https://www.geeksforgeeks.org/python-make-a-list-of-intervals-with-sequential-numbers/
def interval_extract(list):
    list = sorted(set(list))
    range_start = previous_number = list[0]
 
    for number in list[1:]:
        if number == previous_number + 1:
            previous_number = number
        else:
            yield [range_start, previous_number]
            range_start = previous_number = number
    yield [range_start, previous_number]

In [443]:
list(interval_extract(AD_genom_pos))

[[12351602, 12351628], [12417100, 12417154], [12433898, 12434112]]

In [444]:
domain_AD_exons#.sort_values(by = 1)

   0         1         2   3   4  5  6                7
2  3  12351624  12351675  AD NaN  .  +  ENST00000287820
3  3  12379702  12379921  AD NaN  .  +  ENST00000287820
4  3  12434096  12434123  AD NaN  .  +  ENST00000287820

In [445]:
domain_AD_exons["positions"] = [np.arange(start, end) for start, end in zip(domain_AD_exons[1], domain_AD_exons[2])]
domain_AD_exons_expanded = domain_AD_exons[["positions"]].explode("positions")
domain_AD_exons_expanded = domain_AD_exons_expanded.reset_index(drop = True)
domain_AD_exons_expanded

    positions
0    12351624
1    12351625
2    12351626
3    12351627
4    12351628
..        ...
292  12434118
293  12434119
294  12434120
295  12434121
296  12434122

[297 rows x 1 columns]

In [446]:
cds_exons_expanded["AD_bed"] = cds_exons_expanded["positions"].isin(domain_AD_exons_expanded["positions"])
cds_exons_expanded

     positions  prot_pos     AD  AD_bed
0     12434145         1  False   False
1     12434144         1  False   False
2     12434143         1  False   False
3     12434142         2  False   False
4     12434141         2  False   False
...        ...       ...    ...     ...
1513  12351597       505  False   False
1514  12351596       505  False   False
1515  12351595       506  False   False
1516  12351594       506  False   False
1517  12351593       506  False   False

[1518 rows x 4 columns]

In [447]:
cds_exons_expanded[(cds_exons_expanded["AD"]) & (cds_exons_expanded["AD_bed"])]

     positions  prot_pos    AD  AD_bed
33    12434112        12  True    True
34    12434111        12  True    True
35    12434110        12  True    True
36    12434109        13  True    True
37    12434108        13  True    True
38    12434107        13  True    True
39    12434106        14  True    True
40    12434105        14  True    True
41    12434104        14  True    True
42    12434103        15  True    True
43    12434102        15  True    True
44    12434101        15  True    True
45    12434100        16  True    True
46    12434099        16  True    True
47    12434098        16  True    True
48    12434097        17  True    True
49    12434096        17  True    True
1482  12351628       495  True    True
1483  12351627       495  True    True
1484  12351626       495  True    True
1485  12351625       496  True    True
1486  12351624       496  True    True

In [448]:
list(interval_extract(cds_exons_expanded[cds_exons_expanded["AD_bed"]]["prot_pos"]))

[[8, 17], [407, 496]]

In [449]:
# Should be 12-101,495-503

In [450]:
list(interval_extract(cds_exons_expanded[cds_exons_expanded["AD"]]["prot_pos"]))

[[12, 101], [495, 503]]

In [52]:
# Why are they in the wrong place?? Not perfectly reversed either...

In [53]:
505 - 16

489

In [54]:
433-479,118-261

(-46, -143)