In [99]:
import pandas as pd
import protfasta
import requests
import re

1. ENST for all TFs

In [100]:
lambert_TFs = pd.read_csv("../output/lambert_TFs_10-21-24_with_DBD_coords.csv", index_col = 0)
lambert_TFs

,id,ProteinSeq,DBD_coords_merged
0,sp|A0A087WUV0|ZN892_HUMAN Zinc finger protein ...,MEPEGRGSLFEDSDLLHAGNPKENDVTAVLLTPGSQELMIRDMAEA...,"[[221, 243], [249, 271], [277, 299], [305, 327..."
1,sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8...,MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPT...,"[[114, 182], [262, 347]]"
2,sp|A0PJY2|FEZF1_HUMAN Fez family zinc finger p...,MDSSCHNATTKMLATAPARGNMMSTSKPLAFSIERIMARTPEPKAL...,"[[260, 282], [288, 310], [316, 338], [344, 366..."
3,sp|A1A519|F170A_HUMAN Protein FAM170A OS=Homo ...,MKRRQKRKHLENEESQETAEKGGGMSKSQEDALQPGSTRVAKGWSQ...,"[[1, 330]]"
4,sp|A1YPR0|ZBT7C_HUMAN Zinc finger and BTB doma...,MANDIDELIGIPFPNHSSEVLCSLNEQRHDGLLCDVLLVVQEQEYR...,"[[364, 386], [392, 414], [420, 442], [448, 469]]"
...,...,...,...
1608,sp|Q9Y6Q9|NCOA3_HUMAN Nuclear receptor coactiv...,MSGLGENLDPLASDSRKRKLPCDTPGQGLTCSGEKRRREQESKYIE...,"[[31, 83]]"
1609,sp|Q9Y6R6|Z780B_HUMAN Zinc finger protein 780B...,MVHGSVTFRDVAIDFSQEEWECLQPDQRTLYRDVMLENYSHLISLG...,"[[165, 187], [193, 215], [221, 243], [249, 271..."
1610,sp|Q9Y6X0|SETBP_HUMAN SET-binding protein OS=H...,MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGK...,"[[583, 596], [1015, 1027], [1450, 1462]]"
1611,sp|Q9Y6X8|ZHX2_HUMAN Zinc fingers and homeobox...,MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,"[[78, 101], [110, 133], [271, 317], [442, 496]..."
1612,sp|Q9Y6Y1|CMTA1_HUMAN Calmodulin-binding trans...,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,"[[69, 182]]"

In [101]:
lambert_TFs["uniprotID"] = lambert_TFs["id"].str.split("|").str[1]
lambert_TFs

,id,ProteinSeq,DBD_coords_merged,uniprotID
0,sp|A0A087WUV0|ZN892_HUMAN Zinc finger protein ...,MEPEGRGSLFEDSDLLHAGNPKENDVTAVLLTPGSQELMIRDMAEA...,"[[221, 243], [249, 271], [277, 299], [305, 327...",A0A087WUV0
1,sp|A0AVK6|E2F8_HUMAN Transcription factor E2F8...,MENEKENLFCEPHKRGLMKTPLKESTTANIVLAEIQPDFGPLTTPT...,"[[114, 182], [262, 347]]",A0AVK6
2,sp|A0PJY2|FEZF1_HUMAN Fez family zinc finger p...,MDSSCHNATTKMLATAPARGNMMSTSKPLAFSIERIMARTPEPKAL...,"[[260, 282], [288, 310], [316, 338], [344, 366...",A0PJY2
3,sp|A1A519|F170A_HUMAN Protein FAM170A OS=Homo ...,MKRRQKRKHLENEESQETAEKGGGMSKSQEDALQPGSTRVAKGWSQ...,"[[1, 330]]",A1A519
4,sp|A1YPR0|ZBT7C_HUMAN Zinc finger and BTB doma...,MANDIDELIGIPFPNHSSEVLCSLNEQRHDGLLCDVLLVVQEQEYR...,"[[364, 386], [392, 414], [420, 442], [448, 469]]",A1YPR0
...,...,...,...,...
1608,sp|Q9Y6Q9|NCOA3_HUMAN Nuclear receptor coactiv...,MSGLGENLDPLASDSRKRKLPCDTPGQGLTCSGEKRRREQESKYIE...,"[[31, 83]]",Q9Y6Q9
1609,sp|Q9Y6R6|Z780B_HUMAN Zinc finger protein 780B...,MVHGSVTFRDVAIDFSQEEWECLQPDQRTLYRDVMLENYSHLISLG...,"[[165, 187], [193, 215], [221, 243], [249, 271...",Q9Y6R6
1610,sp|Q9Y6X0|SETBP_HUMAN SET-binding protein OS=H...,MESRETLSSSRQRGGESDFLPVSSAKPPAAPGCAGEPLLSTPGPGK...,"[[583, 596], [1015, 1027], [1450, 1462]]",Q9Y6X0
1611,sp|Q9Y6X8|ZHX2_HUMAN Zinc fingers and homeobox...,MASKRKSTTPCMVRTSQVVEQDVPEEVDRAKEKGIGTPQPDVAKDS...,"[[78, 101], [110, 133], [271, 317], [442, 496]...",Q9Y6X8
1612,sp|Q9Y6Y1|CMTA1_HUMAN Calmodulin-binding trans...,MWRAEGKWLPKTSRKSVSQSVFCGTSTYCVLNTVPPIEDDHGNSNS...,"[[69, 182]]",Q9Y6Y1

In [102]:
# Downloading Lambert TF uniprot IDs to upload to uniprot
lambert_TFs[["uniprotID"]].to_csv("../data/lambert_TFs_uniprotIDs.csv", header = None, index = None)

In [103]:
# Loading in the table from uniprot 
TF_ensembl_matches = pd.read_csv("../data/TF_enst_codes.tsv", sep = "\t")
TF_ensembl_matches

,From,Entry,Ensembl
0,A0A087WUV0,A0A087WUV0,ENST00000425953.6;
1,A0AVK6,A0AVK6,ENST00000250024.9;ENST00000527884.5;ENST000006...
2,A0PJY2,A0PJY2,ENST00000427185.2 [A0PJY2-2];ENST00000442488.7...
3,A1A519,A1A519,ENST00000335286.10 [A1A519-2];ENST00000379555....
4,A1YPR0,A1YPR0,ENST00000535628.6;ENST00000586438.5;ENST000005...
...,...,...,...
1608,Q9Y6Q9,Q9Y6Q9,ENST00000371997.3 [Q9Y6Q9-3];ENST00000371998.8...
1609,Q9Y6R6,Q9Y6R6,ENST00000434248.6;ENST00000625684.3;ENST000006...
1610,Q9Y6X0,Q9Y6X0,ENST00000426838.8 [Q9Y6X0-2];ENST00000649279.2...
1611,Q9Y6X8,Q9Y6X8,ENST00000314393.6;
1612,Q9Y6Y1,Q9Y6Y1,ENST00000303635.12 [Q9Y6Y1-1];ENST00000473578....

In [104]:
# Looking at uniprotIDs that have multiple isoforms
multiple_isoforms = TF_ensembl_matches[TF_ensembl_matches["Ensembl"].str.contains("\[") == True]
multiple_isoforms

        From   Entry                                            Ensembl
2     A0PJY2  A0PJY2  ENST00000427185.2 [A0PJY2-2];ENST00000442488.7...
3     A1A519  A1A519  ENST00000335286.10 [A1A519-2];ENST00000379555....
9     A6NFD8  A6NFD8  ENST00000505610.5 [A6NFD8-4];ENST00000515777.6...
16    A6NJ46  A6NJ46  ENST00000518699.4 [A6NJ46-1];ENST00000524115.2...
28    A6NNF4  A6NNF4                      ENST00000594466.6 [A6NNF4-3];
...      ...     ...                                                ...
1606  Q9Y692  Q9Y692  ENST00000294409.2 [Q9Y692-1];ENST00000361872.8...
1607  Q9Y6Q3  Q9Y6Q3  ENST00000374227.8 [Q9Y6Q3-1];ENST00000553380.1...
1608  Q9Y6Q9  Q9Y6Q9  ENST00000371997.3 [Q9Y6Q9-3];ENST00000371998.8...
1610  Q9Y6X0  Q9Y6X0  ENST00000426838.8 [Q9Y6X0-2];ENST00000649279.2...
1612  Q9Y6Y1  Q9Y6Y1  ENST00000303635.12 [Q9Y6Y1-1];ENST00000473578....

[866 rows x 3 columns]

In [105]:
# Looking at uniprotIDs that do not have multiple isoforms
non_isoforms = TF_ensembl_matches[TF_ensembl_matches["Ensembl"].str.contains("\[") == False]
non_isoforms['Ensembl'] = non_isoforms['Ensembl'].str.split(";").str[:-1]

# Arbitrarily choosing the first transcript to keep 
# since all of the transcripts correspond to the same protein
non_isoforms['ENST'] = non_isoforms['Ensembl'].str[0]

# Formatting
non_isoforms = non_isoforms.rename(columns = {"From" : "uniprotID"})
non_isoforms = non_isoforms[["uniprotID", "ENST"]]
non_isoforms

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_11466/1016300479.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_isoforms['Ensembl'] = non_isoforms['Ensembl'].str.split(";").str[:-1]
/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_11466/1016300479.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  non_isoforms['ENST'] = non_isoforms['Ensembl'].str[0]

       uniprotID               ENST
0     A0A087WUV0  ENST00000425953.6
1         A0AVK6  ENST00000250024.9
4         A1YPR0  ENST00000535628.6
5         A2RRD8  ENST00000391781.6
6         A2RU54  ENST00000339992.4
...          ...                ...
1601      Q9Y5V0  ENST00000311212.9
1602      Q9Y5W3  ENST00000248071.6
1605      Q9Y651  ENST00000376945.4
1609      Q9Y6R6  ENST00000434248.6
1611      Q9Y6X8  ENST00000314393.6

[747 rows x 2 columns]

In [106]:
# Now, need to figure out which isoform corresponds to the TF
multiple_isoforms["Ensembl"] = multiple_isoforms["Ensembl"].str.split(";").str[:-1]
multiple_isoforms

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_11466/4148313745.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  multiple_isoforms["Ensembl"] = multiple_isoforms["Ensembl"].str.split(";").str[:-1]

        From   Entry                                            Ensembl
2     A0PJY2  A0PJY2  [ENST00000427185.2 [A0PJY2-2], ENST00000442488...
3     A1A519  A1A519  [ENST00000335286.10 [A1A519-2], ENST0000037955...
9     A6NFD8  A6NFD8  [ENST00000505610.5 [A6NFD8-4], ENST00000515777...
16    A6NJ46  A6NJ46  [ENST00000518699.4 [A6NJ46-1], ENST00000524115...
28    A6NNF4  A6NNF4                     [ENST00000594466.6 [A6NNF4-3]]
...      ...     ...                                                ...
1606  Q9Y692  Q9Y692  [ENST00000294409.2 [Q9Y692-1], ENST00000361872...
1607  Q9Y6Q3  Q9Y6Q3  [ENST00000374227.8 [Q9Y6Q3-1], ENST00000553380...
1608  Q9Y6Q9  Q9Y6Q9  [ENST00000371997.3 [Q9Y6Q9-3], ENST00000371998...
1610  Q9Y6X0  Q9Y6X0  [ENST00000426838.8 [Q9Y6X0-2], ENST00000649279...
1612  Q9Y6Y1  Q9Y6Y1  [ENST00000303635.12 [Q9Y6Y1-1], ENST0000047357...

[866 rows x 3 columns]

In [118]:
# Slow to run

def get_canonical_uniprot_id(uniprot_id):
    url = f"https://rest.uniprot.org/uniprotkb/{uniprot_id}.json"
    response = requests.get(url)
    if response.status_code == 200:
        data = response.json()
        regex_matches = re.findall(r"'isoformIds': \['(.*?)'\]", str(data))
        return(regex_matches[0])
    else:
        return f"Error: {response.status_code}"

i = 0
canonical_ids = []
for uniprotID in multiple_isoforms["From"]:
    if i %100 == 0:
        print(i)
    i += 1
    canonical_ids.append(get_canonical_uniprot_id(uniprotID))
multiple_isoforms["canonical_uniprot_id"] = canonical_ids
multiple_isoforms

In [119]:
multiple_isoforms["num"] = multiple_isoforms["canonical_uniprot_id"].str.split("-").str[1]
multiple_isoforms["num"].value_counts()
# Weird ones are depracated isoform IDs - will save first in those cases

num
1              816
3               19
2               17
4                6
5                4
6                1
1', 'P25912      1
1', 'O75454      1
7                1
Name: count, dtype: int64

In [120]:
multiple_isoforms = multiple_isoforms.drop(columns = "num")

In [121]:
multiple_isoforms_saved = multiple_isoforms.copy(deep = True)

In [122]:
multiple_isoforms["canonical_uniprot_id_cleaned"] = multiple_isoforms["canonical_uniprot_id"].str.replace("'", "").str.split(",").str[0]
multiple_isoforms

,From,Entry,Ensembl,canonical_uniprot_id,canonical_uniprot_id_cleaned
2,A0PJY2,A0PJY2,"[ENST00000427185.2 [A0PJY2-2], ENST00000442488...",A0PJY2-1,A0PJY2-1
3,A1A519,A1A519,"[ENST00000335286.10 [A1A519-2], ENST0000037955...",A1A519-1,A1A519-1
9,A6NFD8,A6NFD8,"[ENST00000505610.5 [A6NFD8-4], ENST00000515777...",A6NFD8-3,A6NFD8-3
16,A6NJ46,A6NJ46,"[ENST00000518699.4 [A6NJ46-1], ENST00000524115...",A6NJ46-1,A6NJ46-1
28,A6NNF4,A6NNF4,[ENST00000594466.6 [A6NNF4-3]],A6NNF4-3,A6NNF4-3
...,...,...,...,...,...
1606,Q9Y692,Q9Y692,"[ENST00000294409.2 [Q9Y692-1], ENST00000361872...",Q9Y692-1,Q9Y692-1
1607,Q9Y6Q3,Q9Y6Q3,"[ENST00000374227.8 [Q9Y6Q3-1], ENST00000553380...",Q9Y6Q3-1,Q9Y6Q3-1
1608,Q9Y6Q9,Q9Y6Q9,"[ENST00000371997.3 [Q9Y6Q9-3], ENST00000371998...",Q9Y6Q9-1,Q9Y6Q9-1
1610,Q9Y6X0,Q9Y6X0,"[ENST00000426838.8 [Q9Y6X0-2], ENST00000649279...",Q9Y6X0-1,Q9Y6X0-1
1612,Q9Y6Y1,Q9Y6Y1,"[ENST00000303635.12 [Q9Y6Y1-1], ENST0000047357...",Q9Y6Y1-1,Q9Y6Y1-1

In [123]:
# Looks good now
multiple_isoforms["num"] = multiple_isoforms["canonical_uniprot_id_cleaned"].str.split("-").str[1]
multiple_isoforms["num"].value_counts()

num
1    818
3     19
2     17
4      6
5      4
6      1
7      1
Name: count, dtype: int64

In [124]:
multiple_isoforms["canonical_uniprot_id"] = multiple_isoforms["canonical_uniprot_id_cleaned"]
multiple_isoforms = multiple_isoforms.drop(columns = "canonical_uniprot_id_cleaned")
multiple_isoforms

,From,Entry,Ensembl,canonical_uniprot_id,num
2,A0PJY2,A0PJY2,"[ENST00000427185.2 [A0PJY2-2], ENST00000442488...",A0PJY2-1,1
3,A1A519,A1A519,"[ENST00000335286.10 [A1A519-2], ENST0000037955...",A1A519-1,1
9,A6NFD8,A6NFD8,"[ENST00000505610.5 [A6NFD8-4], ENST00000515777...",A6NFD8-3,3
16,A6NJ46,A6NJ46,"[ENST00000518699.4 [A6NJ46-1], ENST00000524115...",A6NJ46-1,1
28,A6NNF4,A6NNF4,[ENST00000594466.6 [A6NNF4-3]],A6NNF4-3,3
...,...,...,...,...,...
1606,Q9Y692,Q9Y692,"[ENST00000294409.2 [Q9Y692-1], ENST00000361872...",Q9Y692-1,1
1607,Q9Y6Q3,Q9Y6Q3,"[ENST00000374227.8 [Q9Y6Q3-1], ENST00000553380...",Q9Y6Q3-1,1
1608,Q9Y6Q9,Q9Y6Q9,"[ENST00000371997.3 [Q9Y6Q9-3], ENST00000371998...",Q9Y6Q9-1,1
1610,Q9Y6X0,Q9Y6X0,"[ENST00000426838.8 [Q9Y6X0-2], ENST00000649279...",Q9Y6X0-1,1
1612,Q9Y6Y1,Q9Y6Y1,"[ENST00000303635.12 [Q9Y6Y1-1], ENST0000047357...",Q9Y6Y1-1,1

In [125]:
multiple_isoforms

,From,Entry,Ensembl,canonical_uniprot_id,num
2,A0PJY2,A0PJY2,"[ENST00000427185.2 [A0PJY2-2], ENST00000442488...",A0PJY2-1,1
3,A1A519,A1A519,"[ENST00000335286.10 [A1A519-2], ENST0000037955...",A1A519-1,1
9,A6NFD8,A6NFD8,"[ENST00000505610.5 [A6NFD8-4], ENST00000515777...",A6NFD8-3,3
16,A6NJ46,A6NJ46,"[ENST00000518699.4 [A6NJ46-1], ENST00000524115...",A6NJ46-1,1
28,A6NNF4,A6NNF4,[ENST00000594466.6 [A6NNF4-3]],A6NNF4-3,3
...,...,...,...,...,...
1606,Q9Y692,Q9Y692,"[ENST00000294409.2 [Q9Y692-1], ENST00000361872...",Q9Y692-1,1
1607,Q9Y6Q3,Q9Y6Q3,"[ENST00000374227.8 [Q9Y6Q3-1], ENST00000553380...",Q9Y6Q3-1,1
1608,Q9Y6Q9,Q9Y6Q9,"[ENST00000371997.3 [Q9Y6Q9-3], ENST00000371998...",Q9Y6Q9-1,1
1610,Q9Y6X0,Q9Y6X0,"[ENST00000426838.8 [Q9Y6X0-2], ENST00000649279...",Q9Y6X0-1,1
1612,Q9Y6Y1,Q9Y6Y1,"[ENST00000303635.12 [Q9Y6Y1-1], ENST0000047357...",Q9Y6Y1-1,1

In [126]:
multiple_isoforms_expanded = multiple_isoforms.explode("Ensembl")
multiple_isoforms_expanded

        From   Entry                        Ensembl canonical_uniprot_id num
2     A0PJY2  A0PJY2   ENST00000427185.2 [A0PJY2-2]             A0PJY2-1   1
2     A0PJY2  A0PJY2   ENST00000442488.7 [A0PJY2-1]             A0PJY2-1   1
3     A1A519  A1A519  ENST00000335286.10 [A1A519-2]             A1A519-1   1
3     A1A519  A1A519   ENST00000379555.7 [A1A519-3]             A1A519-1   1
3     A1A519  A1A519   ENST00000695508.1 [A1A519-1]             A1A519-1   1
...      ...     ...                            ...                  ...  ..
1610  Q9Y6X0  Q9Y6X0   ENST00000677130.1 [Q9Y6X0-1]             Q9Y6X0-1   1
1610  Q9Y6X0  Q9Y6X0   ENST00000678152.1 [Q9Y6X0-1]             Q9Y6X0-1   1
1612  Q9Y6Y1  Q9Y6Y1  ENST00000303635.12 [Q9Y6Y1-1]             Q9Y6Y1-1   1
1612  Q9Y6Y1  Q9Y6Y1   ENST00000473578.5 [Q9Y6Y1-3]             Q9Y6Y1-1   1
1612  Q9Y6Y1  Q9Y6Y1   ENST00000557126.5 [Q9Y6Y1-4]             Q9Y6Y1-1   1

[3130 rows x 5 columns]

In [127]:
multiple_isoforms_expanded["Ensembl_uniprot"] = multiple_isoforms_expanded["Ensembl"].str.split("[").str[1].str.split("]").str[0]
multiple_isoforms_expanded

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot
2,A0PJY2,A0PJY2,ENST00000427185.2 [A0PJY2-2],A0PJY2-1,1,A0PJY2-2
2,A0PJY2,A0PJY2,ENST00000442488.7 [A0PJY2-1],A0PJY2-1,1,A0PJY2-1
3,A1A519,A1A519,ENST00000335286.10 [A1A519-2],A1A519-1,1,A1A519-2
3,A1A519,A1A519,ENST00000379555.7 [A1A519-3],A1A519-1,1,A1A519-3
3,A1A519,A1A519,ENST00000695508.1 [A1A519-1],A1A519-1,1,A1A519-1
...,...,...,...,...,...,...
1610,Q9Y6X0,Q9Y6X0,ENST00000677130.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1
1610,Q9Y6X0,Q9Y6X0,ENST00000678152.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1
1612,Q9Y6Y1,Q9Y6Y1,ENST00000303635.12 [Q9Y6Y1-1],Q9Y6Y1-1,1,Q9Y6Y1-1
1612,Q9Y6Y1,Q9Y6Y1,ENST00000473578.5 [Q9Y6Y1-3],Q9Y6Y1-1,1,Q9Y6Y1-3
1612,Q9Y6Y1,Q9Y6Y1,ENST00000557126.5 [Q9Y6Y1-4],Q9Y6Y1-1,1,Q9Y6Y1-4

In [128]:
multiple_isoforms_matched = multiple_isoforms_expanded[multiple_isoforms_expanded["canonical_uniprot_id"] == multiple_isoforms_expanded["Ensembl_uniprot"]]
multiple_isoforms_matched["ENST"] = multiple_isoforms_matched["Ensembl"].str.split(" ").str[0]
multiple_isoforms_matched

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_11466/4196898358.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  multiple_isoforms_matched["ENST"] = multiple_isoforms_matched["Ensembl"].str.split(" ").str[0]

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
2,A0PJY2,A0PJY2,ENST00000442488.7 [A0PJY2-1],A0PJY2-1,1,A0PJY2-1,ENST00000442488.7
3,A1A519,A1A519,ENST00000695508.1 [A1A519-1],A1A519-1,1,A1A519-1,ENST00000695508.1
9,A6NFD8,A6NFD8,ENST00000515777.6 [A6NFD8-3],A6NFD8-3,3,A6NFD8-3,ENST00000515777.6
16,A6NJ46,A6NJ46,ENST00000518699.4 [A6NJ46-1],A6NJ46-1,1,A6NJ46-1,ENST00000518699.4
28,A6NNF4,A6NNF4,ENST00000594466.6 [A6NNF4-3],A6NNF4-3,3,A6NNF4-3,ENST00000594466.6
...,...,...,...,...,...,...,...
1610,Q9Y6X0,Q9Y6X0,ENST00000677068.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677068.1
1610,Q9Y6X0,Q9Y6X0,ENST00000677077.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677077.1
1610,Q9Y6X0,Q9Y6X0,ENST00000677130.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677130.1
1610,Q9Y6X0,Q9Y6X0,ENST00000678152.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000678152.1
1612,Q9Y6Y1,Q9Y6Y1,ENST00000303635.12 [Q9Y6Y1-1],Q9Y6Y1-1,1,Q9Y6Y1-1,ENST00000303635.12

In [156]:
curr_enst_mapping = pd.read_csv("../data/SFARI_TFs_with_ENST_corrected.csv", index_col = 0)
curr_enst_mapping["ENST"] = curr_enst_mapping["ENST"].str.split(".").str[0]
curr_enst_mapping

    uniprotID             ENST
0      Q9H2P0  ENST00000349014
1      Q5TGY3  ENST00000247087
2      Q96QS3  ENST00000379044
3      Q96JM3  ENST00000361283
4      Q96RK0  ENST00000575354
..        ...              ...
117    Q8NEK5  ENST00000366197
118    Q9BR84  ENST00000393883
119    Q68DY1  ENST00000601440
120    Q9Y462  ENST00000276123
121    Q17R98  ENST00000508784

[122 rows x 2 columns]

In [157]:
# Now, check whether current ENST is a match in this table. If not, flag.

for uniprotID, curr_ENST in zip(curr_enst_mapping["uniprotID"], curr_enst_mapping["ENST"]):
    if uniprotID in set(multiple_isoforms_matched["From"]):
        # print(uniprotID)
        # print(curr_ENST)
        
        new_mapping_rows = multiple_isoforms_matched[multiple_isoforms_matched["From"] == uniprotID]
        #display(new_mapping_rows)
        
        if curr_ENST not in set(new_mapping_rows["ENST"]):
            #print(curr_ENST)
            #print(new_mapping_rows["ENST"])
            print(uniprotID + " WRONG")
            display(new_mapping_rows)
            display(curr_enst_mapping[curr_enst_mapping["uniprotID"] == uniprotID])
            
        else:
            print(uniprotID + " ok")

Q96RK0 WRONG

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
1244,Q96RK0,Q96RK0,ENST00000681038.1 [Q96RK0-1],Q96RK0-1,1,Q96RK0-1,ENST00000681038

  uniprotID             ENST
4    Q96RK0  ENST00000575354

Q68CP9 ok
Q9HBZ2 ok
P10275 ok
Q9NR48 ok
Q9UIF8 ok
Q9H165 ok
Q86V15 ok
Q6P1N0 ok
O94983 ok
P49711 ok
P39880 ok
Q13948 ok
O75398 ok
Q07687 ok
Q9H4W6 ok
Q06889 ok
Q92731 ok
Q8TBJ5 ok
Q9H334 ok
O15409 ok
P11308 ok
P78347 ok
Q5T1R4 ok
Q13422 ok
Q9Y2K7 ok
Q9UGL1 ok
O75840 ok
Q03164 ok
Q8NHM5 ok
O60663 ok
Q9UIS9 ok
O95983 ok
O95243 ok
P51608 ok
Q06413 ok
O14770 ok
Q9UL68 ok
Q15788 ok
Q12857 ok
O00712 ok
Q14938 ok
P08235 ok
P43354 ok
Q02548 ok
P26367 ok
P40424 ok
Q96BD5 ok
Q9ULL5 ok
P48380 ok
Q33E94 ok
Q2KHR2 ok
P35398 ok
Q92753 ok
Q01826 ok
Q9UPW6 ok
Q9Y6X0 ok
Q15047 ok
Q96T68 ok
O15266 ok
P18583 ok
P35711 ok
P35712 ok
Q6ZRS2 ok
Q16650 ok
O43435 ok
Q9Y458 ok
Q9UGU0 ok
P15884 ok
Q9NQB0 ok
Q15554 ok
Q6N021 ok
P19532 ok
P10827 ok
Q6ZSZ6 ok
Q05516 ok
Q9HC78 ok
P11473 ok
Q9ULJ3 ok
P17022 ok
O60281 ok
Q96JM2 ok
Q8NEK5 ok
Q9BR84 ok
Q68DY1 ok
Q9Y462 ok
Q17R98 ok

In [158]:
multiple_isoforms_matched[multiple_isoforms_matched["From"] == "Q96RK0"]

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
1244,Q96RK0,Q96RK0,ENST00000681038.1 [Q96RK0-1],Q96RK0-1,1,Q96RK0-1,ENST00000681038

In [159]:
multiple_isoforms_expanded[multiple_isoforms_expanded["From"] == "Q96RK0"]

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot
1244,Q96RK0,Q96RK0,ENST00000575354.6 [Q96RK0-2],Q96RK0-1,1,Q96RK0-2
1244,Q96RK0,Q96RK0,ENST00000681038.1 [Q96RK0-1],Q96RK0-1,1,Q96RK0-1

In [160]:
multiple_isoforms_matched

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
2,A0PJY2,A0PJY2,ENST00000442488.7 [A0PJY2-1],A0PJY2-1,1,A0PJY2-1,ENST00000442488
3,A1A519,A1A519,ENST00000695508.1 [A1A519-1],A1A519-1,1,A1A519-1,ENST00000695508
9,A6NFD8,A6NFD8,ENST00000515777.6 [A6NFD8-3],A6NFD8-3,3,A6NFD8-3,ENST00000515777
16,A6NJ46,A6NJ46,ENST00000518699.4 [A6NJ46-1],A6NJ46-1,1,A6NJ46-1,ENST00000518699
28,A6NNF4,A6NNF4,ENST00000594466.6 [A6NNF4-3],A6NNF4-3,3,A6NNF4-3,ENST00000594466
...,...,...,...,...,...,...,...
1610,Q9Y6X0,Q9Y6X0,ENST00000677068.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677068
1610,Q9Y6X0,Q9Y6X0,ENST00000677077.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677077
1610,Q9Y6X0,Q9Y6X0,ENST00000677130.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677130
1610,Q9Y6X0,Q9Y6X0,ENST00000678152.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000678152
1612,Q9Y6Y1,Q9Y6Y1,ENST00000303635.12 [Q9Y6Y1-1],Q9Y6Y1-1,1,Q9Y6Y1-1,ENST00000303635

In [161]:
curr_enst_mapping

    uniprotID             ENST
0      Q9H2P0  ENST00000349014
1      Q5TGY3  ENST00000247087
2      Q96QS3  ENST00000379044
3      Q96JM3  ENST00000361283
4      Q96RK0  ENST00000575354
..        ...              ...
117    Q8NEK5  ENST00000366197
118    Q9BR84  ENST00000393883
119    Q68DY1  ENST00000601440
120    Q9Y462  ENST00000276123
121    Q17R98  ENST00000508784

[122 rows x 2 columns]

In [162]:
multiple_isoforms_matched["ENST"] =multiple_isoforms_matched["ENST"].str.split(".").str[0]
multiple_isoforms_matched

/var/folders/hw/xx051vr9457c7lrngf2mypgr0000gn/T/ipykernel_11466/2229318489.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  multiple_isoforms_matched["ENST"] =multiple_isoforms_matched["ENST"].str.split(".").str[0]

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
2,A0PJY2,A0PJY2,ENST00000442488.7 [A0PJY2-1],A0PJY2-1,1,A0PJY2-1,ENST00000442488
3,A1A519,A1A519,ENST00000695508.1 [A1A519-1],A1A519-1,1,A1A519-1,ENST00000695508
9,A6NFD8,A6NFD8,ENST00000515777.6 [A6NFD8-3],A6NFD8-3,3,A6NFD8-3,ENST00000515777
16,A6NJ46,A6NJ46,ENST00000518699.4 [A6NJ46-1],A6NJ46-1,1,A6NJ46-1,ENST00000518699
28,A6NNF4,A6NNF4,ENST00000594466.6 [A6NNF4-3],A6NNF4-3,3,A6NNF4-3,ENST00000594466
...,...,...,...,...,...,...,...
1610,Q9Y6X0,Q9Y6X0,ENST00000677068.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677068
1610,Q9Y6X0,Q9Y6X0,ENST00000677077.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677077
1610,Q9Y6X0,Q9Y6X0,ENST00000677130.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677130
1610,Q9Y6X0,Q9Y6X0,ENST00000678152.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000678152
1612,Q9Y6Y1,Q9Y6Y1,ENST00000303635.12 [Q9Y6Y1-1],Q9Y6Y1-1,1,Q9Y6Y1-1,ENST00000303635

In [179]:
for uniprotID in multiple_isoforms_matched["From"]:
    if uniprotID in list(curr_enst_mapping["uniprotID"]):
        print(uniprotID)

O00712
O14770
O15266
O15266
O15266
O15266
O15409
O15409
O15409
O43435
O60281
O60663
O75398
O75840
O94983
O95243
O95983
P08235
P08235
P10275
P10275
P10827
P10827
P11308
P11473
P11473
P15884
P15884
P17022
P17022
P17022
P18583
P19532
P19532
P26367
P26367
P26367
P26367
P26367
P26367
P26367
P35398
P35711
P35712
P35712
P39880
P39880
P40424
P43354
P43354
P48380
P48380
P49711
P49711
P49711
P49711
P49711
P51608
P78347
Q01826
Q01826
Q01826
Q01826
Q01826
Q01826
Q01826
Q01826
Q02548
Q03164
Q05516
Q05516
Q05516
Q05516
Q05516
Q05516
Q05516
Q05516
Q06413
Q06413
Q06413
Q06889
Q07687
Q12857
Q13422
Q13948
Q13948
Q14938
Q15047
Q15554
Q15788
Q15788
Q16650
Q17R98
Q2KHR2
Q33E94
Q5T1R4
Q68CP9
Q68DY1
Q6N021
Q6N021
Q6P1N0
Q6P1N0
Q6ZRS2
Q6ZRS2
Q6ZRS2
Q6ZSZ6
Q86V15
Q8NEK5
Q8NHM5
Q8TBJ5
Q8TBJ5
Q8TBJ5
Q92731
Q92753
Q96BD5
Q96JM2
Q96RK0
Q96T68
Q9BR84
Q9BR84
Q9H165
Q9H334
Q9H334
Q9H334
Q9H334
Q9H334
Q9H334
Q9H4W6
Q9HBZ2
Q9HC78
Q9HC78
Q9HC78
Q9HC78
Q9NQB0
Q9NR48
Q9UGL1
Q9UGU0
Q9UGU0
Q9UGU0
Q9UGU0
Q9UGU0
Q9UIF8
Q9UIS9
Q9UIS9
Q9UIS9
Q9UL68
Q9UL68
Q9UL68
Q9ULJ3
Q9ULJ3
Q9ULJ3
Q9ULL5
Q9UPW6
Q9UPW6
Q9UPW6
Q9UPW6
Q9Y2K7
Q9Y458
Q9Y458
Q9Y458
Q9Y458
Q9Y462
Q9Y462
Q9Y6X0
Q9Y6X0
Q9Y6X0
Q9Y6X0
Q9Y6X0

In [182]:
# Now, need to rebuild mapping table to correct mistakes. keep other ENSTs same as possible.

new_mappings = dict(zip(non_isoforms["uniprotID"], non_isoforms["ENST"]))

for uniprotID, ENST in zip(multiple_isoforms_matched["From"], multiple_isoforms_matched["ENST"]):
    new_mapping_rows = multiple_isoforms_matched[multiple_isoforms_matched["From"] == uniprotID]

    if uniprotID in set(curr_enst_mapping["uniprotID"]):
        curr_ENST = curr_enst_mapping[curr_enst_mapping["uniprotID"] == uniprotID]["ENST"].iloc[0]
        # print(curr_ENST)
        # print(ENST)
        # print()
        if curr_ENST not in set(new_mapping_rows["ENST"]):
            #print(curr_ENST)
            #print(new_mapping_rows["ENST"])
            print(uniprotID + " WRONG")
            display(new_mapping_rows)
            display(curr_enst_mapping[curr_enst_mapping["uniprotID"] == uniprotID])
            new_mappings[uniprotID] = new_mapping_rows["ENST"].iloc[0]
        else:
            new_mappings[uniprotID] = curr_ENST
    else:
        new_mappings[uniprotID] = ENST

Q96RK0 WRONG

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
1244,Q96RK0,Q96RK0,ENST00000681038.1 [Q96RK0-1],Q96RK0-1,1,Q96RK0-1,ENST00000681038

  uniprotID             ENST
4    Q96RK0  ENST00000575354

In [183]:
multiple_isoforms_matched

,From,Entry,Ensembl,canonical_uniprot_id,num,Ensembl_uniprot,ENST
2,A0PJY2,A0PJY2,ENST00000442488.7 [A0PJY2-1],A0PJY2-1,1,A0PJY2-1,ENST00000442488
3,A1A519,A1A519,ENST00000695508.1 [A1A519-1],A1A519-1,1,A1A519-1,ENST00000695508
9,A6NFD8,A6NFD8,ENST00000515777.6 [A6NFD8-3],A6NFD8-3,3,A6NFD8-3,ENST00000515777
16,A6NJ46,A6NJ46,ENST00000518699.4 [A6NJ46-1],A6NJ46-1,1,A6NJ46-1,ENST00000518699
28,A6NNF4,A6NNF4,ENST00000594466.6 [A6NNF4-3],A6NNF4-3,3,A6NNF4-3,ENST00000594466
...,...,...,...,...,...,...,...
1610,Q9Y6X0,Q9Y6X0,ENST00000677068.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677068
1610,Q9Y6X0,Q9Y6X0,ENST00000677077.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677077
1610,Q9Y6X0,Q9Y6X0,ENST00000677130.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000677130
1610,Q9Y6X0,Q9Y6X0,ENST00000678152.1 [Q9Y6X0-1],Q9Y6X0-1,1,Q9Y6X0-1,ENST00000678152
1612,Q9Y6Y1,Q9Y6Y1,ENST00000303635.12 [Q9Y6Y1-1],Q9Y6Y1-1,1,Q9Y6Y1-1,ENST00000303635

In [184]:
new_mappings_df = pd.DataFrame({"uniprotID" : new_mappings.keys(), "ENST" : new_mappings.values()})
new_mappings_df = pd.merge(new_mappings_df, 
                           multiple_isoforms_matched[["From", "canonical_uniprot_id"]],
                          left_on = "uniprotID", right_on = "From", how = "left").drop_duplicates()
new_mappings_df = new_mappings_df.drop(columns = "From")
new_mappings_df["canonical_uniprot_id"] = new_mappings_df["canonical_uniprot_id"].fillna(new_mappings_df["uniprotID"])
new_mappings_df["canonical_uniprot_id_isoform"] = new_mappings_df["canonical_uniprot_id"]
new_mappings_df = new_mappings_df.drop(columns = "canonical_uniprot_id")
new_mappings_df

       uniprotID               ENST canonical_uniprot_id_isoform
0     A0A087WUV0  ENST00000425953.6                   A0A087WUV0
1         A0AVK6  ENST00000250024.9                       A0AVK6
2         A1YPR0  ENST00000535628.6                       A1YPR0
3         A2RRD8  ENST00000391781.6                       A2RRD8
4         A2RU54  ENST00000339992.4                       A2RU54
...          ...                ...                          ...
2127      Q9Y692    ENST00000294409                     Q9Y692-1
2128      Q9Y6Q3    ENST00000374227                     Q9Y6Q3-1
2129      Q9Y6Q9    ENST00000371998                     Q9Y6Q9-1
2130      Q9Y6X0    ENST00000649279                     Q9Y6X0-1
2135      Q9Y6Y1    ENST00000303635                     Q9Y6Y1-1

[1590 rows x 3 columns]

In [185]:
new_mappings_df[new_mappings_df["uniprotID"] == "Q2KHR2"]

     uniprotID             ENST canonical_uniprot_id_isoform
1408    Q2KHR2  ENST00000559447                     Q2KHR2-3

In [186]:
lambert_TFs[~lambert_TFs["uniprotID"].isin(new_mappings_df["uniprotID"])]

,id,ProteinSeq,DBD_coords_merged,uniprotID
42,sp|B1APH4|ZN487_HUMAN Putative zinc finger pro...,MASRPRPRTPSRGPSDLRFRGEAGLRRVFLKKAGGSVSFSDVAVGF...,"[[286, 308], [314, 336]]",B1APH4
110,sp|O43316|PAX4_HUMAN Paired box protein Pax-4 ...,MHQDGISSMNQLGGLFVNGRPLPLDTRQQIVRLAVSGMRPCDISRI...,"[[5, 129], [171, 227]]",O43316
117,sp|O43474|KLF4_HUMAN Krueppel-like factor 4 OS...,MRQPPGESDMAVSDALLPSFSTFASGPAGREKTLRQAGAPNNRWRE...,"[[430, 454], [460, 484], [490, 512]]",O43474
193,sp|O95718|ERR2_HUMAN Steroid hormone receptor ...,MSSDDRHLGSSCGSFIKTEPSSPSSGIDALSHHSPSGSSDASGGFG...,"[[101, 170]]",O95718
195,sp|O95785|WIZ_HUMAN Protein Wiz OS=Homo sapien...,MEGSLAGSLAAPDRPQGPERLPGPAPRENIEGGAEAAEGEGGIFRS...,"[[267, 289], [304, 326], [353, 375], [417, 439...",O95785
212,sp|P05549|AP2A_HUMAN Transcription factor AP-2...,MLWKLTDNIKYEDCEDRHDGTSNGTARLPQLGTVGQSPYTSAPPLS...,"[[209, 409]]",P05549
339,sp|P19544|WT1_HUMAN Wilms tumor protein OS=Hom...,MGSDVRDLNALLPAVPSLGGGGGCALPVSGAAQWAPVLDFAPPGAS...,"[[323, 347], [353, 377], [383, 405], [414, 438]]",P19544
348,sp|P20823|HNF1A_HUMAN Hepatocyte nuclear facto...,MVSKLSQLQTELLAALLESGLSKEALIQALGEPGPYLLAGEGPLDK...,"[[200, 275]]",P20823
408,sp|P36402|TCF7_HUMAN Transcription factor 7 OS...,MPQLDSGGGGAGGGDDLGAPDELLAFQDEGEEQDDKSRDSAAGPER...,"[[269, 337]]",P36402
463,sp|P51814|ZNF41_HUMAN Zinc finger protein 41 O...,MAANGDSPPWSPALAAEGRGSSCEVRRERTPEARIHSVKRYPDLSP...,"[[313, 335], [369, 391], [397, 419], [425, 447...",P51814
474,sp|P52744|ZN138_HUMAN Zinc finger protein 138 ...,MKRHEMVVAKHSALCSRFAQDLWLEQNIKDSFQKVTLSRYGKYGHK...,"[[110, 132], [138, 155], [166, 187], [194, 216...",P52744
495,sp|P56179|DLX6_HUMAN Homeobox protein DLX-6 OS...,MSHSQHSPYLQSYHNSSAAAQTRGDDTDQQKTTVIENGEIRFNGKG...,"[[50, 106]]",P56179
607,sp|Q09FC8|ZN415_HUMAN Zinc finger protein 415 ...,MPELYTEDFIQGCDVGELQEPGLPGVLSYVGAQERALDHRKPSTSS...,"[[292, 314], [320, 342], [348, 370], [376, 398...",Q09FC8
705,sp|Q15583|TGIF1_HUMAN Homeobox protein TGIF1 O...,MVLAQSRVSAGVGSPHCSGSGGGGSDSFPWPASHPGNPQCSFSTAF...,"[[165, 222]]",Q15583
756,sp|Q3B8N5|PROX2_HUMAN Prospero homeobox protei...,MDPNSILLSPQPQICSHLAEACTEGERSSSPPELDRDSPFPWSQVP...,"[[439, 592]]",Q3B8N5
782,sp|Q569K4|Z385B_HUMAN Zinc finger protein 385B...,MNMANFLRGFEEKGIKNDRPEDQLSKEKKKILFSFCEVCNIQLNSA...,"[[157, 181], [348, 372]]",Q569K4
950,sp|Q86UP3|ZFHX4_HUMAN Zinc finger homeobox pro...,METCDSPPISRQENGQSTSKLCGTTQLDNEVPEKVAGMEPDRENSS...,"[[613, 636], [644, 667], [699, 723], [767, 791...",Q86UP3
1062,sp|Q8NCP5|ZBT44_HUMAN Zinc finger and BTB doma...,MGVKTFTHSSSSHSQEMLGKLNMLRNDGHFCDITIRVQDKIFRAHK...,"[[399, 421], [427, 449], [455, 479]]",Q8NCP5
1077,sp|Q8NFW5|DMBX1_HUMAN Diencephalon/mesencephal...,MQHYGVNGYSLHAMNSLSAMYNLHQQAAQQAQHAPDYRPSVHALTL...,"[[72, 128]]",Q8NFW5
1183,sp|Q96I27|ZN625_HUMAN Zinc finger protein 625 ...,MGERLLESKKDHQHGEILTQVPDDMLKKKTPRVKSCGEVSVGHASL...,"[[69, 88], [97, 119], [153, 175], [181, 203], ...",Q96I27
1322,sp|Q9BZB8|CPEB1_HUMAN Cytoplasmic polyadenylat...,MALSLEEEAGRIKDCWDNQEAPALSTCSNANIFRRINAILDNSLDF...,NaN,Q9BZB8
1424,sp|Q9NQV6|PRD10_HUMAN PR domain zinc finger pr...,MDSKDESSHVWPTSAEHEQNAAQVHFVPDTGTVAQIVYTDDQVRPP...,"[[355, 377], [530, 552], [560, 582], [588, 610...",Q9NQV6
1431,sp|Q9NR11|ZN302_HUMAN Zinc finger protein 302 ...,MSQVTFSDVAIDFSHEEWACLDSAQRDLYKDVMVQNYENLVSVGLS...,"[[280, 302], [308, 330], [336, 358], [364, 386...",Q9NR11

In [187]:
len(lambert_TFs[~lambert_TFs["uniprotID"].isin(new_mappings_df["uniprotID"])])

23

In [188]:
new_mappings_df.to_csv("../output/TFs_with_ENST.csv")
new_mappings_df

       uniprotID               ENST canonical_uniprot_id_isoform
0     A0A087WUV0  ENST00000425953.6                   A0A087WUV0
1         A0AVK6  ENST00000250024.9                       A0AVK6
2         A1YPR0  ENST00000535628.6                       A1YPR0
3         A2RRD8  ENST00000391781.6                       A2RRD8
4         A2RU54  ENST00000339992.4                       A2RU54
...          ...                ...                          ...
2127      Q9Y692    ENST00000294409                     Q9Y692-1
2128      Q9Y6Q3    ENST00000374227                     Q9Y6Q3-1
2129      Q9Y6Q9    ENST00000371998                     Q9Y6Q9-1
2130      Q9Y6X0    ENST00000649279                     Q9Y6X0-1
2135      Q9Y6Y1    ENST00000303635                     Q9Y6Y1-1

[1590 rows x 3 columns]