In [15]:
import pandas as pd
import protfasta
import os

In [24]:
filepath = "../outputs/AD_variant_fasta/"
ADs = [f for f in os.listdir(filepath) if os.path.isfile(os.path.join(filepath, f))]
ADs

['GLIS1_Q8NBF1_AD_447-620',
 'RORA_P35398_AD_272-385',
 'VDR_P11473_AD_415-427',
 'SRCAP_Q6ZRS2_AD_2575-3230',
 'THRA_P10827_AD_1-52',
 'YY1_P25490_AD_371-397',
 'NCOA1_Q15788_AD_840-1011',
 'SRCAP_Q6ZRS2_AD_198-1445',
 'ERG_P11308_AD_118-261',
 'CAMTA2_O94983_AD_472-581',
 'ERG_P11308_AD_433-479',
 'EBF3_Q9H4W6_AD_281-360',
 'MSX2_P35548_AD_234-267',
 'YY1_P25490_AD_1-69',
 'MTF1_Q14872_AD_510-624',
 'OTX1_P32242_AD_172-354',
 'ARX_Q96QS3_AD_472-562',
 'MTF1_Q14872_AD_328-509',
 'TBX22_Q9Y458_AD_402-481',
 'NCOA1_Q15788_AD_1241-1385',
 'ARNT2_Q9HBZ2_AD_524-717',
 'TCF4_P15884_AD_1-100',
 'MYT1L_Q9UL68_AD_152-425',
 'CAMTA2_O94983_AD_285-468',
 'IKZF1_Q13422_AD_284-365',
 'TFE3_P19532_AD_1-127',
 'KMT2A-KMT2A-ALL1-HRX-KMT2A-MLL1-CXXC7_Q03164_AD_2782-2921',
 'TCF7L2_Q9NQB0_AD_459-505',
 'NKX2-2_O95096_AD_220-273',
 'DLX3_O60479_AD_199-263',
 'MEF2C_Q06413_AD_87-473',
 'KDM5B_Q9UGL1_AD_1302-1391',
 'TFE3_P19532_AD_212-333',
 'NFIA_Q12857_AD_427-509',
 'KLF7_O75840_AD_2-101',
 'PAX6_P26367_AD_271-422',
 'VDR_P11473_AD_195-238',
 'NR4A2_P43354_AD_584-598',
 'MEIS2_O14770_AD_340-477',
 'NFIX_Q14938_AD_414-502',
 'PITX1_P78337_AD_234-283',
 'TCF7L2_Q9NQB0_AD_1-53',
 'SMAD4_Q13485_AD_30-60',
 'DLX3_O60479_AD_2-91',
 'NR1D1_P20393_AD_8-285',
 'C2D1A_Q6P1N0_AD_22-60',
 'TET2_Q6N021_AD_1582-1751',
 'HIVEP3_Q5T1R4_AD_211-1074',
 'TCF4_P15884_AD_340-400',
 'TCF20_Q9UGU0_AD_1-327',
 'EGR3_Q06889_AD_13-214',
 'CASZ1_Q86V15_AD_31-185',
 'NR4A2_P43354_AD_1-91',
 'SMAD4_Q13485_AD_275-552',
 'PAX5_Q02548_AD_304-358',
 'KLF16_Q9BXK1_AD_209-252',
 'ESR2_Q92731_AD_1-148',
 'ESR2_Q92731_AD_304-500',
 'NCOA1_Q15788_AD_1-93',
 'NFE2L3-NF2L3_Q9Y4A8_AD_252-451',
 'TFE3_P19532_AD_472-575']

In [25]:
num_vars = []

for AD in ADs:
    print(AD)
    AD_fasta_dict = protfasta.read_fasta("../outputs/AD_variant_fasta/" + AD)
    num_vars.append((len(AD_fasta_dict)))

GLIS1_Q8NBF1_AD_447-620
RORA_P35398_AD_272-385
VDR_P11473_AD_415-427
SRCAP_Q6ZRS2_AD_2575-3230
THRA_P10827_AD_1-52
YY1_P25490_AD_371-397
NCOA1_Q15788_AD_840-1011
SRCAP_Q6ZRS2_AD_198-1445
ERG_P11308_AD_118-261
CAMTA2_O94983_AD_472-581
ERG_P11308_AD_433-479
EBF3_Q9H4W6_AD_281-360
MSX2_P35548_AD_234-267
YY1_P25490_AD_1-69
MTF1_Q14872_AD_510-624
OTX1_P32242_AD_172-354
ARX_Q96QS3_AD_472-562
MTF1_Q14872_AD_328-509
TBX22_Q9Y458_AD_402-481
NCOA1_Q15788_AD_1241-1385
ARNT2_Q9HBZ2_AD_524-717
TCF4_P15884_AD_1-100
MYT1L_Q9UL68_AD_152-425
CAMTA2_O94983_AD_285-468
IKZF1_Q13422_AD_284-365
TFE3_P19532_AD_1-127
KMT2A-KMT2A-ALL1-HRX-KMT2A-MLL1-CXXC7_Q03164_AD_2782-2921
TCF7L2_Q9NQB0_AD_459-505
NKX2-2_O95096_AD_220-273
DLX3_O60479_AD_199-263
MEF2C_Q06413_AD_87-473
KDM5B_Q9UGL1_AD_1302-1391
TFE3_P19532_AD_212-333
NFIA_Q12857_AD_427-509
KLF7_O75840_AD_2-101
PAX6_P26367_AD_271-422
VDR_P11473_AD_195-238
NR4A2_P43354_AD_584-598
MEIS2_O14770_AD_340-477
NFIX_Q14938_AD_414-502
PITX1_P78337_AD_234-283
TCF7L2_Q9NQB0_AD_1-53
SMAD4_Q13485_AD_30-60
DLX3_O60479_AD_2-91
NR1D1_P20393_AD_8-285
C2D1A_Q6P1N0_AD_22-60
TET2_Q6N021_AD_1582-1751
HIVEP3_Q5T1R4_AD_211-1074
TCF4_P15884_AD_340-400
TCF20_Q9UGU0_AD_1-327
EGR3_Q06889_AD_13-214
CASZ1_Q86V15_AD_31-185
NR4A2_P43354_AD_1-91
SMAD4_Q13485_AD_275-552
PAX5_Q02548_AD_304-358
KLF16_Q9BXK1_AD_209-252
ESR2_Q92731_AD_1-148
ESR2_Q92731_AD_304-500
NCOA1_Q15788_AD_1-93
NFE2L3-NF2L3_Q9Y4A8_AD_252-451
TFE3_P19532_AD_472-575

In [29]:
AD_df = pd.DataFrame({"AD" : ADs, "num_vars" : num_vars})
AD_df

                                AD  num_vars
0          GLIS1_Q8NBF1_AD_447-620        75
1           RORA_P35398_AD_272-385        14
2            VDR_P11473_AD_415-427         2
3        SRCAP_Q6ZRS2_AD_2575-3230       336
4              THRA_P10827_AD_1-52        13
..                             ...       ...
56            ESR2_Q92731_AD_1-148        50
57          ESR2_Q92731_AD_304-500        76
58            NCOA1_Q15788_AD_1-93        19
59  NFE2L3-NF2L3_Q9Y4A8_AD_252-451        98
60          TFE3_P19532_AD_472-575        40

[61 rows x 2 columns]

In [31]:
AD_df["GeneName"] = AD_df["AD"].str.split("_").str[0]
AD_df["uniprotID"] = AD_df["AD"].str.split("_").str[1]
AD_df["Location"] = AD_df["AD"].str.split("_").str[-1]
AD_df

,AD,num_vars,GeneName,uniprotID,Location
0,GLIS1_Q8NBF1_AD_447-620,75,GLIS1,Q8NBF1,447-620
1,RORA_P35398_AD_272-385,14,RORA,P35398,272-385
2,VDR_P11473_AD_415-427,2,VDR,P11473,415-427
3,SRCAP_Q6ZRS2_AD_2575-3230,336,SRCAP,Q6ZRS2,2575-3230
4,THRA_P10827_AD_1-52,13,THRA,P10827,1-52
...,...,...,...,...,...
56,ESR2_Q92731_AD_1-148,50,ESR2,Q92731,1-148
57,ESR2_Q92731_AD_304-500,76,ESR2,Q92731,304-500
58,NCOA1_Q15788_AD_1-93,19,NCOA1,Q15788,1-93
59,NFE2L3-NF2L3_Q9Y4A8_AD_252-451,98,NFE2L3-NF2L3,Q9Y4A8,252-451
60,TFE3_P19532_AD_472-575,40,TFE3,P19532,472-575