In [1]:
import pandas as pd
import protfasta

In [3]:
known_ADs = pd.read_csv("../../output/known_ADs_considering_isoforms_and_canonical.csv")
known_ADs

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes
0,ABRAXAS1,121,200,Q6UWZ7,[['Q6UWZ7']],ENST00000321945,Q6UWZ7,DelRosso et al.,CR,LQEHFSNQDLVFLLLTPSIITESCSTHRLEHSLYKPQKGLFHRVPL...,NaN
1,AEBP1,1088,1158,Q8IUX7,[['Q8IUX7']],NaN,Q8IUX7,Staller Activity Data,TF,EVVTEFGTEVEPEFGTKVEPEFETQLEPEFETQLEPEFEEEEEEEK...,NaN
2,AHCTF1,1445,1698,Q8WYP5,"[['Q8WYP5'], ['Q8WYP5']]",nan / nan,Q8WYP5 / Q8WYP5,"PMID: 11952839, Soto / transcriptionalactivity...",TF,IRANDNKSMADVLGDGGNSSLTISEGPIVSERRLNQEVALNLKEDH...,NaN
3,AHR,118,126,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,LLQALNGFV,NaN
4,AHR,266,268,P35869,[['P35869']],NaN,P35869,"transcriptionalactivity_regions.txt, GSL",TF,FAI,NaN
...,...,...,...,...,...,...,...,...,...,...,...
739,ZSCAN20,262,341,P17040,"[['P17040', 'P17040-3']]",ENST00000361328,P17040,DelRosso et al.,TF,PSNTSEKEQGPEFWGLSLINSGKRSTADYSLDNEPAQALTWRDSRA...,NaN
740,ZXDA,572,699,P98168,"[['P98168'], ['P98168']]",nan / nan,P98168 / P98168 / P98168,"PMID: 17493635, Soto / R4TA_regions.txt / acti...",TF,QDLLAQLEAANSLTPSSELTSQRQNDLSDAEIVSLFSDVPDSTSAA...,NaN
741,ZXDB,576,703,P98169,[['P98169']],NaN,P98169 / P98169,"R4TA_regions.txt / activation_regions.txt, GSL",TF,QDLLAQLEAANSLTPSSELTSQRQNDLSDAEIVSLFSDVPDSTSAA...,NaN
742,ZXDC,579,688,Q2QGD7,"[['Q2QGD7', 'Q2QGD7-2'], ['Q2QGD7', 'Q2QGD7-2']]",nan / nan,Q2QGD7 / Q2QGD7 / Q2QGD7,"PMID: 16600381, Soto / R4TA_regions.txt / acti...",TF,DSPLVLGTAATVLQQGSFSVDDVQTVSAGALGCLVALPMKNLSDDP...,NaN
743,c-Jun/AP-1,238,257,P05412,[['P05412']],NaN,P05412,"Choi 2000 list, GSL",TF,ETPPLSPIDMESQERIKAER,NaN

In [4]:
known_ADs[known_ADs["Gene"] == "VDR"]

,Gene,Start,End,uniprotID,Matching Isoforms,Canonical Transcript ID,orig_uniprotID,Reference,TileType,ProteinRegionSeq,Notes
691,VDR,415,427,P11473,[['P11473']],NaN,P11473,"PMID: 15908514, Soto",TF,TPLVLEVFGNEIS,NaN
692,VDR,195,238,P11473,"[['P11473'], ['P11473']]",nan / nan,P11473 / P11473,"Choi 2000 list OR uniprot. check, GSL / Stalle...",TF,DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,NaN

In [5]:
AD_1_variant_dict = protfasta.read_fasta("../outputs/AD_variant_fasta/VDR_P11473_AD_195-238")
AD_1 = pd.DataFrame({"id" : AD_1_variant_dict.keys(),
                    "seq" : AD_1_variant_dict.values()})
AD_1

                            id                                           seq
0   g.47855697G>C(p.Leu230Val)  DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI
1   g.47855720G>C(p.Ser222Cys)  DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI
2   g.47855721A>C(p.Ser222Ala)  DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI
3   g.47855725C>G(p.Glu220Asp)  DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI
4   g.47855742G>A(p.Pro215Ser)  DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI
5   g.47855743G>T(p.Asp214Glu)  DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI
6   g.47855744T>C(p.Asp214Gly)  DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI
7   g.47855753T>C(p.Asp211Gly)  DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI
8   g.47855762C>T(p.Ser208Asn)  DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI
9   g.47855773A>C(p.Asn204Lys)  DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
10  g.47855773A>T(p.Asn204Lys)  DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
11  g.47855775T>G(p.Asn204His)  DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
12  g.47855782G>T(p.Ser201Arg)  DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
13  g.47855792T>C(p.Asp198Gly)  DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
14  g.47855793C>T(p.Asp198Asn)  DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
15  g.47855795A>G(p.Met197Thr)  DMTDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
16  g.47855798A>G(p.Met196Thr)  DTMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI
17  g.47855800G>C(p.Asp195Glu)  EMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI

In [6]:
AD_1["full_prot_pos"] = AD_1["id"].str.extract('.*(\d\d\d).*')
AD_1

,id,seq,full_prot_pos
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198
15,g.47855795A>G(p.Met197Thr),DMTDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,197
16,g.47855798A>G(p.Met196Thr),DTMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,196
17,g.47855800G>C(p.Asp195Glu),EMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,195

In [18]:
AD_1["domain_pos"] = AD_1["full_prot_pos"].astype(int) - 195 + 1
AD_1

,id,seq,full_prot_pos,domain_pos,orig,var
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230,36,L,V
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222,28,S,C
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222,28,S,A
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220,26,E,D
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215,21,P,S
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214,20,D,E
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214,20,D,G
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211,17,D,G
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208,14,S,N
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,H
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201,7,S,R
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,G
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,N
15,g.47855795A>G(p.Met197Thr),DMTDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,197,3,M,T
16,g.47855798A>G(p.Met196Thr),DTMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,196,2,M,T
17,g.47855800G>C(p.Asp195Glu),EMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,195,1,D,E

In [19]:
AD_1["orig"] = AD_1["id"].str.extract('.*(...)\d\d\d.*')
AD_1["orig"] =AD_1["orig"].str.upper()
AD_1["var"] = AD_1["id"].str.extract('.*\d\d\d(...).*')
AD_1["var"] =AD_1["var"].str.upper()
AD_1

,id,seq,full_prot_pos,domain_pos,orig,var
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230,36,LEU,VAL
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222,28,SER,CYS
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222,28,SER,ALA
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220,26,GLU,ASP
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215,21,PRO,SER
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214,20,ASP,GLU
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214,20,ASP,GLY
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211,17,ASP,GLY
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208,14,SER,ASN
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,ASN,LYS
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,ASN,LYS
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,ASN,HIS
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201,7,SER,ARG
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,ASP,GLY
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,ASP,ASN
15,g.47855795A>G(p.Met197Thr),DMTDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,197,3,MET,THR
16,g.47855798A>G(p.Met196Thr),DTMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,196,2,MET,THR
17,g.47855800G>C(p.Asp195Glu),EMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,195,1,ASP,GLU

In [20]:
d = {'CYS': 'C', 'ASP': 'D', 'SER': 'S', 'GLN': 'Q', 'LYS': 'K',
     'ILE': 'I', 'PRO': 'P', 'THR': 'T', 'PHE': 'F', 'ASN': 'N', 
     'GLY': 'G', 'HIS': 'H', 'LEU': 'L', 'ARG': 'R', 'TRP': 'W', 
     'ALA': 'A', 'VAL':'V', 'GLU': 'E', 'TYR': 'Y', 'MET': 'M'}

In [21]:
AD_1["var"] = AD_1["var"].replace(d)
AD_1["orig"] = AD_1["orig"].replace(d)

In [31]:
AD_1

,id,seq,full_prot_pos,domain_pos,orig,var,mutation
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230,36,L,V,L36V
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222,28,S,C,S28C
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222,28,S,A,S28A
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220,26,E,D,E26D
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215,21,P,S,P21S
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214,20,D,E,D20E
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214,20,D,G,D20G
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211,17,D,G,D17G
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208,14,S,N,S14N
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N10K
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N10K
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,H,N10H
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201,7,S,R,S7R
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,G,D4G
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,N,D4N
15,g.47855795A>G(p.Met197Thr),DMTDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,197,3,M,T,M3T
16,g.47855798A>G(p.Met196Thr),DTMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,196,2,M,T,M2T
17,g.47855800G>C(p.Asp195Glu),EMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,195,1,D,E,D1E

In [33]:
# The sequence in the plasmid actually does not have the first 3 positions, so adjusting
AD_1["seq_plasmid"] = AD_1["seq"].str[3:]
AD_1["domain_pos_plasmid"] = AD_1["domain_pos"] - 3
AD_1

,id,seq,full_prot_pos,domain_pos,orig,var,mutation,seq_plasmid,domain_pos_plasmid
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230,36,L,V,L36V,DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,33
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222,28,S,C,S28C,DSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,25
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222,28,S,A,S28A,DSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,25
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220,26,E,D,E26D,DSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,23
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215,21,P,S,P21S,DSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,18
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214,20,D,E,D20E,DSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,17
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214,20,D,G,D20G,DSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,17
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211,17,D,G,D17G,DSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,14
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208,14,S,N,S14N,DSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,11
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N10K,DSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N10K,DSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,H,N10H,DSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201,7,S,R,S7R,DSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,4
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,G,D4G,GSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,1
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,N,D4N,NSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,1
15,g.47855795A>G(p.Met197Thr),DMTDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,197,3,M,T,M3T,DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,0
16,g.47855798A>G(p.Met196Thr),DTMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,196,2,M,T,M2T,DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,-1
17,g.47855800G>C(p.Asp195Glu),EMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,195,1,D,E,D1E,DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,-2

In [35]:
AD_1_plasmid_df = AD_1[AD_1["domain_pos_plasmid"] > 0]
AD_1_plasmid_df

,id,seq,full_prot_pos,domain_pos,orig,var,mutation,seq_plasmid,domain_pos_plasmid
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230,36,L,V,L36V,DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,33
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222,28,S,C,S28C,DSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,25
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222,28,S,A,S28A,DSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,25
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220,26,E,D,E26D,DSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,23
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215,21,P,S,P21S,DSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,18
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214,20,D,E,D20E,DSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,17
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214,20,D,G,D20G,DSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,17
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211,17,D,G,D17G,DSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,14
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208,14,S,N,S14N,DSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,11
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N10K,DSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N10K,DSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,H,N10H,DSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201,7,S,R,S7R,DSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,4
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,G,D4G,GSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,1
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,N,D4N,NSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,1

In [40]:
AD_1_plasmid_df["mutation"] = AD_1_plasmid_df["orig"].astype(str) + AD_1_plasmid_df["domain_pos_plasmid"].astype(str) + AD_1_plasmid_df["var"].astype(str)
AD_1_plasmid_df

<ipython-input-40-18c1df8f4aa3>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  AD_1_plasmid_df["mutation"] = AD_1_plasmid_df["orig"].astype(str) + AD_1_plasmid_df["domain_pos_plasmid"].astype(str) + AD_1_plasmid_df["var"].astype(str)

,id,seq,full_prot_pos,domain_pos,orig,var,mutation,seq_plasmid,domain_pos_plasmid
0,g.47855697G>C(p.Leu230Val),DMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,230,36,L,V,L33V,DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHVADLVSYSI,33
1,g.47855720G>C(p.Ser222Cys),DMMDSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,222,28,S,C,S25C,DSSSFSNLDLSEEDSDDPSVTLELCQLSMLPHLADLVSYSI,25
2,g.47855721A>C(p.Ser222Ala),DMMDSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,222,28,S,A,S25A,DSSSFSNLDLSEEDSDDPSVTLELAQLSMLPHLADLVSYSI,25
3,g.47855725C>G(p.Glu220Asp),DMMDSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,220,26,E,D,E23D,DSSSFSNLDLSEEDSDDPSVTLDLSQLSMLPHLADLVSYSI,23
4,g.47855742G>A(p.Pro215Ser),DMMDSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,215,21,P,S,P18S,DSSSFSNLDLSEEDSDDSSVTLELSQLSMLPHLADLVSYSI,18
5,g.47855743G>T(p.Asp214Glu),DMMDSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,214,20,D,E,D17E,DSSSFSNLDLSEEDSDEPSVTLELSQLSMLPHLADLVSYSI,17
6,g.47855744T>C(p.Asp214Gly),DMMDSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,214,20,D,G,D17G,DSSSFSNLDLSEEDSDGPSVTLELSQLSMLPHLADLVSYSI,17
7,g.47855753T>C(p.Asp211Gly),DMMDSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,211,17,D,G,D14G,DSSSFSNLDLSEEGSDDPSVTLELSQLSMLPHLADLVSYSI,14
8,g.47855762C>T(p.Ser208Asn),DMMDSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,208,14,S,N,S11N,DSSSFSNLDLNEEDSDDPSVTLELSQLSMLPHLADLVSYSI,11
9,g.47855773A>C(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N7K,DSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
10,g.47855773A>T(p.Asn204Lys),DMMDSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,K,N7K,DSSSFSKLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
11,g.47855775T>G(p.Asn204His),DMMDSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,204,10,N,H,N7H,DSSSFSHLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,7
12,g.47855782G>T(p.Ser201Arg),DMMDSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,201,7,S,R,S4R,DSSRFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,4
13,g.47855792T>C(p.Asp198Gly),DMMGSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,G,D1G,GSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,1
14,g.47855793C>T(p.Asp198Asn),DMMNSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,198,4,D,N,D1N,NSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI,1

In [41]:
" ".join(AD_1_plasmid_df["mutation"])

'L33V S25C S25A E23D P18S D17E D17G D14G S11N N7K N7K N7H S4R D1G D1N'

In [43]:
from Bio.Seq import Seq

In [44]:
Seq("GACAGCAGCAGCTTCAGCAACCTGGACCTGAGCGAGGAGGACAGCGACGACCCCAGCGTGACCCTGGAGCTGAGCCAGCTGAGCATGCTGCCCCACCTGGCCGACCTGGTGAGCTACAGCATC").translate()

Seq('DSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSI')

In [23]:
AD_2_variant_dict = protfasta.read_fasta("../outputs/AD_variant_fasta/VDR_P11473_AD_415-427")
AD_2 = pd.DataFrame({"id" : AD_2_variant_dict.keys(),
                    "seq" : AD_2_variant_dict.values()})
AD_2

                           id            seq
0  g.47844750G>A(p.Ser427Phe)  TPLVLEVFGNEIF
1  g.47844759T>C(p.Asn424Ser)  TPLVLEVFGSEIS

In [25]:
AD_2["full_prot_pos"] = AD_2["id"].str.extract('.*(\d\d\d).*')
AD_2["domain_pos"] = AD_2["full_prot_pos"].astype(int) - 415 + 1
AD_2["orig"] = AD_2["id"].str.extract('.*(...)\d\d\d.*')
AD_2["orig"] =AD_2["orig"].str.upper()
AD_2["var"] = AD_2["id"].str.extract('.*\d\d\d(...).*')
AD_2["var"] =AD_2["var"].str.upper()
AD_2["var"] = AD_2["var"].replace(d)
AD_2["orig"] = AD_2["orig"].replace(d)

AD_2["orig"].astype(str) + AD_2["domain_pos"].astype(str) + AD_2["var"].astype(str)

0    S13F
1    N10S
dtype: object